from schema import skill

DOMAIN = {
    "id": "strategy",
    "title": "Strategy and leadership",
    "summary": "Direction, choices, board narrative, and operating cadence for founders and executive teams.",
    "keywords": ["strategy", "leadership", "board", "planning", "okrs"],
}

SKILLS = [
    skill(
        "strategic-plan-builder",
        "Strategic Plan Builder",
        "Turn a vague ambition into a one-page strategy with a real choice, a few bets, and what you will not do.",
        "one-page strategic plan",
        ["write a strategy", "annual strategy", "where should we focus", "strategic plan", "what not to do"],
        ["Current position: customers, revenue motion, constraints", "The decision the plan must settle", "Time horizon, usually 12 months", "What is already committed and cannot move"],
        [
            "Name the choice: State the strategic question in one sentence, such as which customer, motion, or market gets scarce attention this year.",
            "Bound the horizon: Use the horizon the user gave. If they did not, use 12 months and say so. Do not write a five-year vision deck unless they asked for one.",
            "Record the playing field: Summarize only facts the user supplied: who pays, why they pay, and what constraint is binding. Mark anything else as an assumption.",
            "Make a few bets: Recommend no more than three bets. Each bet needs an owner, a cost, a leading indicator, and a kill criterion.",
            "Write the nos: List at least three attractive options you are explicitly not doing, and the reason. A plan without nos is a wish list.",
            "Set the review: Name the forum and cadence that will revisit the bets. Strategy that is never reviewed is a poster.",
        ],
        [
            "Listing every initiative the team already wanted and calling it a strategy.",
            "Confusing a vision statement with a choice.",
            "Inventing market size to make the plan look bigger.",
        ],
        "A founder says the company should 'become the platform for mid-market clinics' but the team is still closing the first ten customers by hand.",
        "A one-page plan that chooses a beachhead, names three bets, lists what will wait, and sets a 90-day review with kill criteria.",
        ["scenario-planning", "portfolio-prioritization", "annual-planning-cycle"],
        ["A request for a financial model only", "A legal entity decision that needs counsel"],
    ),
    skill(
        "okrs-and-scorecard",
        "OKRs and Scorecard",
        "Write objectives and key results that measure outcomes, then pair them with a weekly operating scorecard.",
        "OKR set and weekly scorecard",
        ["write OKRs", "objectives and key results", "quarterly goals", "scorecard", "are these OKRs any good"],
        ["Team or company the goals belong to", "Quarter or cycle dates", "Strategy bets the goals must serve", "Baseline for each proposed metric"],
        [
            "Anchor to strategy: Reject any objective that does not serve a stated bet. If there is no strategy, say so and write provisional goals marked as such.",
            "Limit the set: Recommend one to three objectives. More than five key results per objective is a task list.",
            "Separate outcomes from tasks: Rewrite 'launch the feature' into the customer or business result the launch is supposed to change.",
            "Make results measurable: Each key result needs a baseline, a target, a source, and a date. If the baseline is unknown, the first result is to instrument it.",
            "Add a scorecard: Choose three to seven weekly numbers an owner can update without a special project. OKRs are the destination. The scorecard is the steering wheel.",
            "Assign owners: One owner per key result. Shared ownership is how results go missing.",
        ],
        [
            "Using OKRs as a performance-rating weapon in the same breath as writing them.",
            "Setting targets with no baseline.",
            "Filling the scorecard with vanity metrics nobody acts on.",
        ],
        "A product lead wants Q3 OKRs and offers 'ship mobile app' and 'improve NPS' with no baseline.",
        "Two outcome objectives, key results with baselines and sources, and a weekly scorecard of five numbers tied to those results.",
        ["north-star-metric", "operating-cadence", "strategic-plan-builder"],
    ),
    skill(
        "board-memo-writer",
        "Board Memo Writer",
        "Draft a board memo that leads with the decision, the ask, and the risk, not a recap of activity.",
        "board decision memo",
        ["board memo", "board paper", "write to the board", "director update", "board pre-read"],
        ["The decision or update type", "The ask, if any, including amount and timing", "Facts, misses, and risks the user can support", "What the board already knows"],
        [
            "Lead with the ask: The first paragraph states the decision, the recommendation, and what happens if the board does nothing.",
            "Separate news from noise: Include only changes since the last meeting that affect cash, risk, customers, or the strategy.",
            "Show the downside: Name the main risk, the early warning sign, and the mitigation already in motion. Do not hide a miss in an appendix.",
            "Give options when there is a decision: Two or three options, with cost, time, and what each gives up. Recommend one.",
            "Keep it short: Aim for two pages. Move tables and backup to a short appendix the memo points to.",
            "Mark drafts: Label the memo as a draft for the CEO or chair to approve. Do not invent resolutions or votes.",
        ],
        [
            "Opening with a company history the board already knows.",
            "Burying a cash problem under product updates.",
            "Writing a resolution as if the board had already voted.",
        ],
        "The CEO needs a pre-read asking the board to approve a hiring pause until a renewal lands.",
        "A two-page memo with the ask, the cash implication, two alternatives, and the decision requested at the meeting.",
        ["board-meeting-facilitator", "decision-log", "executive-one-pager"],
    ),
    skill(
        "board-meeting-facilitator",
        "Board Meeting Facilitator",
        "Design a board agenda that spends time on decisions and exceptions, and produce a clean minute skeleton afterward.",
        "board agenda and minute skeleton",
        ["board agenda", "run a board meeting", "board minutes", "director meeting plan"],
        ["Meeting length", "Decisions required", "Materials already prepared", "Attendees and anyone recused"],
        [
            "Sort the agenda: Put decisions first, exceptions second, and FYI last. Cut FYI that was already in the pre-read.",
            "Timebox: Assign minutes to each item. Leave a buffer. Do not schedule more decisions than the meeting can actually make.",
            "Name the owner: Every item has a presenter and the decision type: approve, advise, or inform.",
            "Handle conflicts: If the user flags a conflict or recusal, put it on the agenda before the related item. Do not draft legal conclusions about the conflict.",
            "Prepare minutes: After the meeting, or from the user's notes, record decisions, dissents, and owners. Do not write color commentary.",
            "Close the loop: List actions with owners and dates. A meeting without actions was a briefing.",
        ],
        [
            "An agenda that is a tour of every department.",
            "Minutes that invent consensus.",
            "Skipping recusals the user already identified.",
        ],
        "A chair has 90 minutes and three decisions: a budget revision, a key hire, and a customer concentration risk.",
        "A timed agenda with decisions first, plus a minute skeleton that records the ask, the vote line, and actions.",
        ["board-memo-writer", "decision-log", "operating-cadence"],
    ),
    skill(
        "decision-log",
        "Decision Log",
        "Record an important decision so a later reader can see the choice, the alternatives, and what would reopen it.",
        "decision record",
        ["decision log", "document this decision", "why did we choose", "decision record", "ADR for the business"],
        ["The decision in one sentence", "Alternatives considered", "Facts used", "Who decided and when"],
        [
            "State the decision: One sentence, past or present tense, with the date and the decider. No preamble.",
            "Record alternatives: At least one real alternative that was rejected, and why. If none was considered, say that plainly.",
            "Cite facts: List only evidence the user provided. Do not backfill a rationale that sounds smarter than the actual one.",
            "Name the reopen condition: What new fact would justify revisiting the decision. Decisions without reopen conditions become dogma.",
            "Note consequences: Who must change what by when because of this decision.",
            "File it: Suggest a location and a title the team can find later. Do not create a new bureaucracy around the log.",
        ],
        [
            "Rewriting history to make a messy decision look inevitable.",
            "Logging every tiny choice.",
            "Omitting the rejected alternative.",
        ],
        "A leadership team chose to pause a second product line after a renewal slipped, and they want the reason written down.",
        "A one-page decision record with the choice, the alternative, the cash fact that drove it, and the condition that would reopen it.",
        ["architecture-decision-record", "board-memo-writer", "founder-decision-review"],
    ),
    skill(
        "scenario-planning",
        "Scenario Planning",
        "Build a small set of contrasting futures and the early signs that tell you which one you are in.",
        "scenario set with signposts",
        ["scenario planning", "what if", "upside and downside cases", "strategic scenarios"],
        ["The decision the scenarios inform", "Two or three uncertainties that actually matter", "Time horizon", "Facts and constraints already known"],
        [
            "Pick uncertainties: Choose two uncertainties the user believes could break the plan. Do not brainstorm twenty.",
            "Build three or four futures: A base case, a downside, and an upside are enough. Name each future so people can talk about it.",
            "Stay internally consistent: A downside case cannot also assume the best sales cycle and the cheapest hiring market unless the user says so.",
            "Find signposts: For each scenario, name two observable signs that would tell you it is unfolding. Signs must be measurable in the user's world.",
            "Pre-commit moves: For the downside, write the move you would make if the signpost hits, including what you would stop.",
            "Do not pretend precision: Scenarios are stories with logic, not forecasts. Label them as such.",
        ],
        [
            "A single forecast with a confidence interval dressed up as scenarios.",
            "Scenarios that differ only by a percentage.",
            "Inventing macro statistics to decorate the story.",
        ],
        "A services firm wants to know how to plan hiring if a key public-sector contract is delayed by two quarters.",
        "Three named scenarios, the signposts for each, and a hiring move tied to the delay signpost rather than to hope.",
        ["strategic-plan-builder", "sensitivity-and-scenarios", "war-room-brief"],
    ),
    skill(
        "competitive-strategy",
        "Competitive Strategy",
        "Explain how you win against a named alternative, including the status quo, without inventing competitor secrets.",
        "competitive strategy note",
        ["competitive strategy", "how do we win", "competitor response", "against the status quo"],
        ["The customer and the job to be done", "Alternatives the buyer actually considers, including doing nothing", "Proof the user has", "Where you refuse to compete"],
        [
            "Name the real alternative: Include 'do nothing' and internal tools, not only famous vendors. Use competitor facts the user supplied.",
            "Find the deciding job: State the job the buyer hires a product to do, in their words if you have them.",
            "Choose where to be different: Recommend one difference that is costly for the alternative to copy. A longer feature list is not a strategy.",
            "Say where you will lose: Name the buyer for whom you are the wrong choice. That protects the team from bad deals.",
            "Define proof: What evidence would make a skeptical buyer believe the difference. If the user has no proof, the next step is to get it, not to claim it.",
            "Avoid dirty tricks: Do not draft deception, fake switching campaigns, or attacks you cannot substantiate.",
        ],
        [
            "Inventing a competitor's revenue, roadmap, or weakness.",
            "Competing on a checklist of features with no tradeoff.",
            "Trash-talk copy that the user cannot defend.",
        ],
        "A team keeps losing to spreadsheets, not to the named software rival, and wants a strategy note.",
        "A note that treats the spreadsheet as the main alternative, names the buyer you will not chase, and lists the proof still missing.",
        ["competitive-battlecard", "positioning-statement", "market-entry-assessment"],
    ),
    skill(
        "market-entry-assessment",
        "Market Entry Assessment",
        "Test whether a new segment or geography deserves a real bet, using the user's evidence rather than a borrowed market-size slide.",
        "market entry assessment",
        ["should we enter", "new market", "new segment", "geographic expansion", "market entry"],
        ["The segment definition", "Why now, in the user's words", "Access to the first customers", "Cost and constraint of a test"],
        [
            "Define the segment: Who is in, who is out, and what problem they already spend time or money on. Vague 'SMBs' is not a segment.",
            "Test access: How will you reach the first ten buyers? If the answer is 'marketing later,' the entry plan is not ready.",
            "Estimate the cost of learning: Recommend a small test with a budget, a time box, and a kill metric. Do not build a full business case on invented TAM.",
            "Name the adaptation: What must change in offer, pricing, support, or compliance. Flag legal and regulatory questions for a specialist rather than answering them.",
            "Compare with the current bet: What existing work slows down if you enter. Opportunity cost belongs in the memo.",
            "Recommend: Enter with a test, wait, or decline. One recommendation, with the fact that would change it.",
        ],
        [
            "Leading with a huge market-size number from memory.",
            "Treating a segment slide as permission to hire a full team.",
            "Ignoring regulatory or licensing questions by waving them away.",
        ],
        "A domestic software company asks whether to open a UK motion next quarter because two inbound leads arrived.",
        "An assessment that defines the segment, prices a 90-day test, names the compliance questions for counsel, and does not treat two leads as a market.",
        ["strategic-plan-builder", "scenario-planning", "go-to-market-brief"],
    ),
    skill(
        "ma-screening",
        "M&A Screening",
        "Screen an acquisition or partnership idea before anyone spends serious diligence money.",
        "M&A screening memo",
        ["acquisition screen", "should we buy", "M&A idea", "partnership versus build", "diligence kickoff"],
        ["The target or partner, as the user described it", "The strategic gap this would fill", "Known price range or the fact that price is unknown", "Constraints: cash, talent, regulation"],
        [
            "State the gap: What customer, capability, or time problem is this meant to solve. If the gap is unclear, stop and say the screen cannot proceed.",
            "Compare alternatives: Buy, partner, or build. Recommend the path that fits the gap, not the most exciting one.",
            "List what must be true: Five things that must be true for the deal to be rational, and how a later diligence workstream would test each one.",
            "Flag walk-away issues: Customer concentration, key-person risk, unclear IP, or a price that only works with a fantasy synergy. Use only issues the user raised or that follow directly from their facts.",
            "Do not invent valuation: If you illustrate a range, label every multiple as the user's assumption. Never present a number as a fair price.",
            "Define the next step: A cheap question to answer before hiring advisors, not a full diligence plan disguised as a screen.",
        ],
        [
            "Building a synergy model from imagined revenue.",
            "Acting as an investment bank or fairness-opinion writer.",
            "Ignoring build and partner options because a banker sent a teaser.",
        ],
        "A CEO received a teaser for a small competitor and wants to know if it is even worth a conversation.",
        "A screening memo with the strategic gap, buy-versus-build, five must-be-true tests, and a single next question before advisors are hired.",
        ["investment-memo", "competitive-strategy", "decision-log"],
        ["A request to hide the deal from required approvers", "Valuation advice presented as a fairness opinion"],
    ),
    skill(
        "corporate-narrative",
        "Corporate Narrative",
        "Write the company story employees and customers can repeat without sliding into hype.",
        "corporate narrative",
        ["company narrative", "our story", "why we exist", "elevator pitch for the company", "narrative memo"],
        ["Who the company serves", "The problem in the customer's language", "Proof points the user can stand behind", "What the company refuses to claim"],
        [
            "Start with the customer: The first lines describe the customer's tension, not the founding myth.",
            "State the change: What is different because the company exists. One change, not a list of values.",
            "Add proof: Two proof points the user supplied. If proof is thin, write a humbler story rather than borrowing fake logos.",
            "Write three lengths: A sentence, a paragraph, and a half page. They must agree with each other.",
            "Remove hype: Delete 'revolutionary,' 'unique,' and unearned category claims. Specific beats grand.",
            "Note the audience: Offer a variant for employees if the user needs one, focused on how daily work connects to the change.",
        ],
        [
            "A founding story that never mentions the customer.",
            "Claims of market leadership without evidence.",
            "A different story for every channel.",
        ],
        "A team has five conflicting About pages and wants one narrative before a launch.",
        "A sentence, a paragraph, and a half page that share one customer change and only the proof the user provided.",
        ["positioning-statement", "messaging-house", "brand-voice-guide"],
    ),
    skill(
        "operating-cadence",
        "Operating Cadence",
        "Design the weekly, monthly, and quarterly meetings that keep a strategy alive without drowning the team.",
        "operating cadence",
        ["operating cadence", "meeting rhythm", "weekly business review", "how should leadership meet"],
        ["Team size and roles", "Decisions that currently stall", "Existing meetings the user wants to keep or kill", "Time zone or capacity constraints"],
        [
            "Start from decisions: List the decisions that are late or relitigated. Meetings exist to make those decisions, not to share updates that could be written.",
            "Design three loops: A weekly operating review, a monthly performance look, and a quarterly strategy check. Do not add a fourth loop unless the user has a specific failure it solves.",
            "Define inputs: Each meeting gets a one-page pre-read and a named owner. No pre-read, no meeting.",
            "Kill overlaps: Recommend which current meetings to cancel or merge. A new cadence on top of the old one is how calendars die.",
            "Set the tone: Issues are raised with a proposed move. Status theater is out of scope.",
            "Pilot it: Recommend a six-week pilot and what would prove the cadence is worth keeping.",
        ],
        [
            "Adding standups to every team by default.",
            "A cadence with no cancelled meetings.",
            "Dashboards that take longer to prepare than the meeting itself.",
        ],
        "A 40-person company has eleven recurring leadership meetings and still misses hiring and cash decisions.",
        "A three-loop cadence, the meetings to cancel, the pre-read owner for each loop, and a six-week pilot test.",
        ["meeting-operating-system", "okrs-and-scorecard", "weekly-review"],
    ),
    skill(
        "executive-one-pager",
        "Executive One-Pager",
        "Compress a complex issue into a single page a busy executive can act on.",
        "executive one-pager",
        ["one-pager", "exec summary", "brief the CEO", "single page brief"],
        ["The audience and the decision they can make", "The source material or the user's facts", "The recommendation if there is one", "What must not be cut"],
        [
            "Identify the reader: Write for the person who will decide, not for every stakeholder who wants a mention.",
            "Put the point first: The top of the page states the situation, the recommendation, and the ask.",
            "Support with three facts: Choose the three facts that would change the decision if they were wrong. Move the rest out.",
            "Name the tradeoff: What the recommendation costs or risks. A one-pager with no tradeoff is an advertisement.",
            "End with the action: Owner, date, and what 'done' means.",
            "Cut jargon: If a term is internal, translate it. The reader should not need a glossary.",
        ],
        [
            "Shrinking a long memo by reducing the font.",
            "Including every stakeholder's paragraph.",
            "Hiding the ask in the last line.",
        ],
        "A general manager needs the CEO to approve a price test and currently has a 14-page appendix.",
        "A one-page brief with the test, the risk, three facts, and a yes-or-no ask.",
        ["board-memo-writer", "decision-log", "management-reporting-pack"],
    ),
    skill(
        "stakeholder-map",
        "Stakeholder Map",
        "Map who can help or block a decision, and how to engage them without manipulation.",
        "stakeholder map and engagement plan",
        ["stakeholder map", "who do we need", "political landscape", "influence map"],
        ["The decision or change", "People involved, as the user named them", "Known concerns", "The engagement the user is willing to do"],
        [
            "List actors: Include operators, approvers, customers, and skeptics. Do not limit the map to people who already agree.",
            "Assess influence and interest: Use the user's judgment. Do not psychoanalyze people or invent motives.",
            "Write the concern: For each important actor, state the concern in language they would recognize.",
            "Plan honest engagement: What they need to know, what you need from them, and when. No tricks, no concealed agendas.",
            "Find the gap: Who has not been heard and could stop the work late. Late surprise is the failure mode this skill prevents.",
            "Keep it private and respectful: Mark the map as internal. Do not write insults or personal rumors.",
        ],
        [
            "A map that is only the organizing committee.",
            "Engagement tactics that hide material facts.",
            "Invented personalities.",
        ],
        "A plant manager wants to change the shift pattern and knows the union rep and two supervisors are uneasy.",
        "A map of actors, their stated concerns, and a plain engagement sequence that does not hide the effect on hours.",
        ["change-leadership", "stakeholder-update", "internal-comms-plan"],
    ),
    skill(
        "change-leadership",
        "Change Leadership",
        "Plan how a specific change will be adopted, including who loses something and how you will support them.",
        "change adoption plan",
        ["change management", "rollout to the org", "people side of change", "adoption plan"],
        ["The change in concrete terms", "Who must work differently", "What they lose or must learn", "Sponsor and timing"],
        [
            "Describe the change in behavior: What will a specific person do differently on a Tuesday. If you cannot say, the change is not defined.",
            "Name losses: Status, skill, convenience, or headcount effects the user has acknowledged. Do not pretend a hard change is only upside.",
            "Pick sponsors: A sponsor who will not repeat the message is not a sponsor. Recommend a cadence of visible reinforcement.",
            "Support the middle: Managers need a script, a FAQ grounded in decisions already made, and a way to raise exceptions.",
            "Measure adoption: Choose one or two observable behaviors, not a survey score alone.",
            "Plan resistance: Treat resistance as information. Design a channel for it. Do not draft ways to punish questions.",
        ],
        [
            "A change plan that is only a slide about urgency.",
            "Hiding job impact.",
            "Measuring adoption with a single enthusiasm survey.",
        ],
        "Finance is moving the company from monthly spreadsheets to a shared close calendar and managers are ignoring it.",
        "An adoption plan that names Tuesday behaviors, manager support, the loss of local flexibility, and one observable adoption metric.",
        ["stakeholder-map", "internal-comms-plan", "operating-cadence"],
    ),
    skill(
        "culture-diagnostic",
        "Culture Diagnostic",
        "Describe how the culture actually behaves, using evidence, and name one habit worth changing.",
        "culture diagnostic",
        ["culture problem", "how we work", "culture diagnostic", "values versus behavior"],
        ["Incidents or examples the user witnessed", "Stated values, if any", "What the user wants culture to help the business do", "Limits on what they are willing to change"],
        [
            "Prefer stories to adjectives: Collect specific moments. 'We are innovative' is not evidence.",
            "Compare stated and lived: Where values and promotions, meetings, or incidents disagree, write the gap carefully and without gossip.",
            "Tie culture to work: Which business result is harder because of the current habit.",
            "Choose one habit: Recommend one behavior to change in the next quarter, with a manager ritual that reinforces it. Do not propose a rebrand of the values poster.",
            "Watch power: Note whether the habit is rewarded in who gets promoted or excused. Use only examples the user gave.",
            "Avoid armchair psychology: Do not diagnose individuals. Describe systems and norms.",
        ],
        [
            "A new values list with no behavior change.",
            "Blaming 'culture' for a single underperforming person.",
            "Inventing survey results.",
        ],
        "A founder says the culture is 'like a family' but missed commitments have no consequence.",
        "A diagnostic that uses the user's incidents, names the accountability gap, and proposes one ritual rather than a new values poster.",
        ["engagement-survey-readout", "change-leadership", "operating-cadence"],
    ),
    skill(
        "portfolio-prioritization",
        "Portfolio Prioritization",
        "Rank a set of initiatives by constraint, not by who argued last, and make the cut visible.",
        "prioritized portfolio",
        ["prioritize initiatives", "what should we stop", "portfolio review", "too many projects"],
        ["The list of initiatives", "The scarce resource: people, cash, or attention", "Strategy bets", "Which items are truly mandatory"],
        [
            "Name the constraint: Prioritize against the scarce resource. If everything is priority one, nothing is.",
            "Separate mandatory from chosen: Regulatory, contractual, or safety work the user confirms as mandatory sits above discretionary bets.",
            "Score simply: Use impact on the stated bet, cost in the scarce resource, and time to evidence. Do not use a fake-precise 14-factor model.",
            "Make the cut: Recommend a stop, pause, and continue list. A ranking with no cut is not prioritization.",
            "Show the losers: Write why attractive work is waiting. Silent cuts become shadow projects.",
            "Set a reopen date: The portfolio is reviewed on a date, not whenever someone escalates.",
        ],
        [
            "Prioritizing by executive volume.",
            "Keeping every project and 'focusing' in the narrative only.",
            "A weighted model nobody can explain.",
        ],
        "A leadership team has 22 active initiatives and 9 managers, and wants a portfolio cut before annual planning.",
        "A continue, pause, and stop list tied to manager capacity, with the reason each stopped item is waiting.",
        ["prioritization-rice", "strategic-plan-builder", "resource-plan"],
    ),
    skill(
        "north-star-metric",
        "North Star Metric",
        "Choose one north-star metric that reflects customer value, plus a handful of input metrics the team can move.",
        "north-star metric definition",
        ["north star metric", "one metric that matters", "company metric", "what should we optimize"],
        ["How the customer gets value", "Current candidate metrics and their definitions", "Known ways the metric could be gamed", "Who will own it"],
        [
            "Start from value: The north star should move when customers get value, not merely when the company books activity.",
            "Reject vanity: Signups, page views, and raw revenue are usually poor north stars unless the user can show they match value in this business.",
            "Write the definition: Numerator, denominator, inclusion rules, and source. A metric without a definition will be argued every week.",
            "Add inputs: Three to five input metrics a team can influence this month. The north star is a result, not a lever.",
            "Name the gaming risk: How a team could hit the number and hurt the customer. Add a counter-metric.",
            "Do not worship it: State what the north star does not measure, so finance and quality concerns are not erased.",
        ],
        [
            "Picking revenue because it is easy to explain to a board.",
            "A north star with no definition.",
            "No counter-metric, so the number can be gamed.",
        ],
        "A marketplace is debating GMV versus successful jobs completed as the company metric.",
        "A definition of the chosen metric, why the alternative loses, three input metrics, and a counter-metric that protects quality.",
        ["okrs-and-scorecard", "metric-definition", "product-analytics-spec"],
    ),
    skill(
        "war-room-brief",
        "War Room Brief",
        "Stand up a short-lived response when a serious business issue needs daily focus, without turning panic into a permanent process.",
        "war-room brief",
        ["war room", "crisis brief", "we have a serious issue", "daily response plan"],
        ["What happened, in facts", "Who is affected", "Decisions needed in the next 48 hours", "Who is in charge"],
        [
            "State the incident: Facts, time, impact, and what is still unknown. No blame paragraph at the top.",
            "Set the objective: What 'stable' means in the next 48 hours. A war room without an objective becomes a standing meeting.",
            "Assign roles: One owner, a decision maker, a communications owner, and a note taker. Everyone else is on call, not in the room.",
            "List decisions: Only decisions that cannot wait. Park strategy redesign.",
            "Plan communications: Who needs to know what, internally and externally, and what must be approved before it is said. Do not draft deceptive reassurance.",
            "Set an end: A review point when the war room dissolves back into normal cadence.",
        ],
        [
            "Inviting the whole company into the war room.",
            "Promising customers facts you do not have.",
            "Leaving the war room running for months.",
        ],
        "A key supplier missed a shipment and three major customers will stock out within a week.",
        "A 48-hour brief with an owner, the decisions required today, a truthful customer message draft, and an end condition.",
        ["incident-response-coord", "stakeholder-update", "shortage-playbook"],
    ),
    skill(
        "founder-decision-review",
        "Founder Decision Review",
        "Help a founder pressure-test a lonely decision before they announce it.",
        "founder decision review",
        ["founder decision", "am I about to make a mistake", "pressure-test this call", "solo founder choice"],
        ["The decision and the deadline", "Alternatives still open", "What the founder is afraid of", "Whose advice they have already heard"],
        [
            "Restate the decision: Reflect it back in one sentence so you are reviewing the real choice.",
            "Separate fear from fact: List facts the founder supplied and the fear they named. Do not therapize. Do not flatter.",
            "Stress the downside: What happens in 90 days if this is wrong, and is that downside reversible.",
            "Look for a missing voice: Who is affected and has not been asked. Recommend asking them if there is time. Do not role-play their consent.",
            "Offer a pre-mortem: Assume it failed and list the three most plausible reasons, using the founder's context.",
            "Leave the decision with them: Recommend, but state that the call is theirs. Do not pretend to be a board.",
        ],
        [
            "Telling the founder what they want to hear.",
            "Expanding a hiring choice into a life-coaching session.",
            "Inventing investor or customer opinions.",
        ],
        "A solo founder wants to fire their first salesperson before a board meeting in two days and is unsure.",
        "A review that restates the decision, separates facts from fear, names reversibility, and leaves the call with the founder.",
        ["decision-log", "founder-operating-review", "executive-one-pager"],
    ),
    skill(
        "annual-planning-cycle",
        "Annual Planning Cycle",
        "Design a planning calendar that connects strategy, money, and team capacity without a three-month planning fog.",
        "annual planning cycle",
        ["annual planning", "planning calendar", "budget season", "how to run planning"],
        ["Fiscal year dates", "Who must approve the plan", "Inputs that were late last year", "Non-negotiable constraints"],
        [
            "Work backward from approval: Put the board or CEO decision date on the calendar first, then the drafts that must precede it.",
            "Sequence the work: Strategy choices before budget numbers. Headcount after the bets, not before.",
            "Limit rounds: Recommend two draft cycles, not an open-ended negotiation. Name what is frozen after each round.",
            "Define inputs: Each function provides a short template, not a private spreadsheet format. Specify the owner and due date.",
            "Integrate capacity: The plan is not done when the slides match. It is done when named people can carry the work.",
            "Retrospective slot: Add a one-hour review of the planning process itself after approval, while the pain is fresh.",
        ],
        [
            "Starting with departmental wish lists.",
            "Six rounds of budget negotiation.",
            "A plan that ignores who will do the work.",
        ],
        "A COO wants next year's planning to finish before December instead of drifting into February.",
        "A backward calendar from the approval date, two draft rounds, required inputs, and an explicit capacity check.",
        ["strategic-plan-builder", "budget-variance-review", "workforce-plan"],
    ),
    skill(
        "go-to-market-brief",
        "Go-to-Market Brief",
        "Brief a launch or a new motion so sales, product, and marketing are aiming at the same buyer and offer.",
        "go-to-market brief",
        ["go to market", "GTM brief", "launch motion", "how do we take this to market"],
        ["The offer", "The buyer and the trigger event", "The channel the team can actually staff", "The date and the success signal"],
        [
            "Define the buyer: One primary buyer. Secondary audiences are noted, not given equal weight.",
            "State the offer: What they buy, what is out of the box, and what problem it solves this quarter.",
            "Pick a channel: Recommend the channel the team can staff now. A multi-channel plan with no owners is a poster.",
            "Align enablement: What sales needs to say, what marketing must not claim, and what product must be true on day one.",
            "Set a learning window: The first 30 or 60 days are a test. Name the number that would stop the motion.",
            "Name gaps: Pricing, legal, support, or proof that is not ready. Do not launch those gaps into silence.",
        ],
        [
            "A GTM plan that is only a channel list.",
            "Claims marketing cannot support.",
            "No kill metric.",
        ],
        "A product is ready for a design-partner release and the teams disagree on who the buyer is.",
        "A brief with one buyer, one staffed channel, enablement limits, and a 60-day kill metric.",
        ["launch-plan", "positioning-statement", "sales-playbook"],
    ),
    skill(
        "executive-offsite-design",
        "Executive Offsite Design",
        "Design an offsite that leaves with decisions, not a pile of flip charts.",
        "offsite design and pre-work",
        ["executive offsite", "leadership offsite", "strategy day", "offsite agenda"],
        ["The decisions the offsite must produce", "Attendees", "Length of the offsite", "Sensitive topics the user wants handled carefully"],
        [
            "Pick two outcomes: An offsite that tries to settle culture, budget, product, and hiring will settle none of them.",
            "Send pre-work: A short memo per outcome, read before the day. The offsite is for disagreement and decision, not live briefing.",
            "Design the room: Small working sessions before a plenary decision. Give skeptics a scheduled voice so they do not ambush the end.",
            "Facilitate the choice: Each session ends with a recommended choice, the alternative, and what would reopen it.",
            "Protect breaks: Decisions get worse when the agenda is a forced march. Say so if the user has overpacked the day.",
            "Leave with owners: The last block assigns owners and dates. No owner means the topic was a discussion, and the notes should say that.",
        ],
        [
            "An offsite with no pre-read and twelve topics.",
            "Trust falls instead of the decision the team came to make.",
            "Notes that imply agreement when the room did not agree.",
        ],
        "A CEO has one day with the exec team and wants to leave with a focus decision and a hiring principle.",
        "An agenda with two outcomes, pre-reads, a decision block for each, and a closing owner assignment.",
        ["board-meeting-facilitator", "strategic-plan-builder", "decision-log"],
    ),
]
