from schema import skill

DOMAIN = {
    "id": "finance",
    "title": "Finance",
    "summary": "Cash, forecasts, unit economics, and management reporting for operators and FP&A. Not investment advice.",
    "keywords": ["finance", "fpna", "forecast", "cash", "budget", "metrics"],
}

SKILLS = [
    skill(
        "cash-flow-forecast",
        "Cash Flow Forecast",
        "Build a 13-week direct cash forecast from collections and commitments, not from accrual revenue.",
        "13-week cash forecast",
        ["13-week cash", "cash forecast", "when do we run out of money", "weekly cash", "liquidity forecast"],
        ["Opening cash by entity and currency", "Receivables and the user's collection experience", "Payroll, tax, rent, and debt dates", "Approved payables and known one-offs"],
        [
            "Lock the frame: Use 13 weeks unless the user asked for another horizon. Record opening cash by account. Do not net cash against a credit line unless they treat that line as cash.",
            "Forecast collections: Inflows come from expected cash collected, not from revenue booked. Use the user's lag. If they have no history, mark a stated assumption and keep it visible.",
            "List commitments: Payroll, taxes, rent, debt service, and approved payables are committed. Discretionary spend sits in a separate row.",
            "Show one-offs: Financing, capex, and owner transfers get their own lines. Do not bury them in operations.",
            "Roll forward: Opening plus inflows minus outflows equals closing, every week. Flag any week under the user's minimum buffer.",
            "Stress it: Slip collections by the delay the user fears, and pull one large payment forward. Name the first week that breaks. Do not call the forecast a guarantee.",
        ],
        [
            "Starting from an accrual P&L and calling it cash.",
            "Hiding a financing need inside 'other'.",
            "Presenting a single unstressed line as certainty.",
        ],
        "A founder asks whether they can hire two people next month without missing payroll.",
        "A weekly cash table, the buffer breach week under a collection slip, and a hire condition tied to cash rather than to optimism.",
        ["runway-and-burn", "working-capital", "budget-variance-review"],
        ["Tax advice", "A promise of funding"],
    ),
    skill(
        "budget-variance-review",
        "Budget Variance Review",
        "Explain what moved versus budget in a way an operator can act on, separating timing from true misses.",
        "budget variance review",
        ["budget variance", "why are we off budget", "actual versus plan", "monthly variance"],
        ["Budget and actuals for the period", "The user's explanation of one-off items", "Materiality threshold", "Who needs the review"],
        [
            "Set materiality: Ignore noise under the threshold the user names. If they name none, propose one and label it as a proposal.",
            "Bridge the gap: Start at budget and walk to actual in a few drivers. Volume, price, timing, and one-offs are the usual buckets. Use only drivers you can support.",
            "Separate timing: A bill that landed early is not the same as a cost that will repeat. Say which variances reverse.",
            "Find the forecast impact: Which variances should change the outlook, and which should not.",
            "Ask for an action: Each material miss gets an owner and a response, or an explicit decision to accept it.",
            "Write for the reader: A CEO gets the bridge and the decisions. A department lead gets their lines, not the whole company essay.",
        ],
        [
            "A line-by-line dump with no bridge.",
            "Treating every timing difference as a performance failure.",
            "Inventing a 'market' explanation without evidence.",
        ],
        "Marketing is 18 percent over budget and the CMO says it is timing of an event invoice.",
        "A bridge that isolates the invoice timing, states whether the full-year outlook changes, and names any remaining true overspend.",
        ["forecast-accuracy", "management-reporting-pack", "cash-flow-forecast"],
    ),
    skill(
        "unit-economics",
        "Unit Economics",
        "Calculate contribution economics for one real unit the business sells, and show which assumption dominates.",
        "unit economics sheet",
        ["unit economics", "contribution margin", "CAC payback", "do we make money per customer"],
        ["The unit: customer, order, location, or contract", "Price and direct costs the user can support", "Acquisition cost definition", "Retention or repeat evidence, if any"],
        [
            "Define the unit: Say exactly what one unit is. Mixing orders and customers in one margin is how teams fool themselves.",
            "Build contribution: Price minus costs that vary with the unit. Keep fixed overhead out of the unit and show it separately.",
            "Treat acquisition honestly: Include the costs the user says are required to win the unit. Do not ignore discounts and onboarding if they are real.",
            "Show payback only if retention is known: If retention is a guess, label payback as illustrative and do not lead with it.",
            "Sensitivity: Name the one assumption that swings the answer. Recommend improving that input, not decorating the model.",
            "Decision: Say whether the unit, on the user's numbers, funds its own acquisition and delivery. Do not invent a benchmark to declare victory.",
        ],
        [
            "A lifetime value built on an invented retention curve.",
            "Forgetting discounts, refunds, or implementation cost.",
            "Comparing the result to a generic SaaS benchmark from memory.",
        ],
        "A subscription team wants to know if a new annual plan clears contribution after onboarding labor.",
        "A unit sheet that defines the customer-year, keeps overhead out, and shows payback only to the extent retention evidence exists.",
        ["pricing-margin-bridge", "saas-metrics-pack", "break-even-analysis"],
    ),
    skill(
        "pricing-margin-bridge",
        "Pricing and Margin Bridge",
        "Trace price, mix, and cost so a margin change has a cause and a commercial response.",
        "price-mix-cost bridge",
        ["margin bridge", "price mix cost", "why did margin fall", "pricing review"],
        ["Revenue and cost for two periods", "Price and volume detail if available", "Known mix shifts", "Discount or rebate practice"],
        [
            "Start with the margin change: State gross margin or contribution change in the user's currency and in points.",
            "Separate price, volume, and mix: Use the detail the user has. If mix cannot be seen, say the bridge is incomplete rather than forcing a fake split.",
            "Put discounts in price: A discount is a price decision. Do not hide it in cost.",
            "Isolate cost inflation: Input cost changes sit on their own step, with the user's evidence.",
            "Recommend one commercial move: A price test, a mix target, or a cost action. Not all three at full strength unless the user has capacity.",
            "Flag customer impact: Who would feel the move. Do not draft deceptive pricing.",
        ],
        [
            "A margin story with no bridge.",
            "Blaming mix when the data cannot show mix.",
            "Recommending a price increase with no customer consequence.",
        ],
        "Gross margin fell two points and sales says it was only product mix.",
        "A bridge that shows what portion is mix, price, and cost on the available data, plus one commercial response.",
        ["unit-economics", "pricing-packaging", "budget-variance-review"],
    ),
    skill(
        "fundraising-model",
        "Fundraising Model",
        "Lay out how much cash a raise needs to buy, what it funds, and what remains unresolved. Not a valuation.",
        "fundraising use-of-proceeds model",
        ["fundraising model", "use of proceeds", "how much should we raise", "runway raise"],
        ["Current cash and monthly burn the user stands behind", "The plan the raise is meant to fund", "Target months of runway", "Known financing terms, if any"],
        [
            "Start from the plan: The raise follows the operating plan, not the other way around. If there is no plan, say the amount cannot be justified yet.",
            "Build a monthly cash view: Use the user's costs. Separate hiring that is required for the plan from hiring that is optional.",
            "Add a buffer: Recommend a stated buffer for timing slips. Call it a buffer, not a pretend precision.",
            "Use of proceeds: Group the money into a few uses a investor or lender can audit later. No 'miscellaneous growth' bucket over a small share unless the user insists, and then flag it.",
            "Do not value the company: If the user supplies a price, you may show dilution math as arithmetic. Do not invent a valuation.",
            "State what the money will not do: The milestones this raise does not buy. Overclaiming the plan is how raises become stories.",
        ],
        [
            "Choosing a raise amount because it sounds normal.",
            "Inventing a pre-money valuation.",
            "A use-of-proceeds slide that does not tie to the cash model.",
        ],
        "A founder wants to raise '18 months of runway' and has a hiring plan that is not in the current burn.",
        "A monthly cash view, a recommended buffer, a use-of-proceeds grouping, and an explicit statement that valuation is outside this skill.",
        ["runway-and-burn", "investment-memo", "cash-flow-forecast"],
        ["Investment advice", "Inventing investor demand"],
    ),
    skill(
        "runway-and-burn",
        "Runway and Burn",
        "Compute cash runway from a defined burn, and show how hiring or a slipped receipt changes the date.",
        "runway note",
        ["runway", "burn rate", "how long is our cash", "cash out date"],
        ["Cash on hand", "Which expenses are in burn", "Expected receipts the user wants included or excluded", "Upcoming committed hires"],
        [
            "Define burn: State whether burn is cash operating burn, and whether financing or one-offs are excluded. Write the definition before the number.",
            "Use a recent window: Prefer the user's last complete months over a single unusual week. Note if a month was distorted.",
            "Compute the date: Cash divided by the defined monthly burn, then adjust for known receipts if the user wants a receipt-inclusive view. Show both if they differ.",
            "Add the hire: Show the runway date with and without the committed hire. Do not hide the effect.",
            "Name the lever: The one change that moves the date most, based on their numbers.",
            "Avoid false comfort: A credit line is not cash unless they describe it as available and unconditional.",
        ],
        [
            "One runway number with no definition.",
            "Treating a facility as cash without the user's confirmation.",
            "Ignoring a hire that is already committed.",
        ],
        "A CEO says runway is 14 months, but the figure excludes two signed offers starting next month.",
        "Two runway dates, the burn definition, and the effect of the signed offers shown separately.",
        ["cash-flow-forecast", "fundraising-model", "workforce-plan"],
    ),
    skill(
        "three-statement-model",
        "Three-Statement Model",
        "Sketch how profit, cash, and the balance sheet stay tied together, at the level the user can actually support.",
        "linked three-statement sketch",
        ["three statement model", "integrated forecast", "P&L balance sheet cash flow", "financial model structure"],
        ["Historical statements or the fact that they are unavailable", "Forecast horizon", "Debt, capex, and working-capital drivers", "What decision the model must support"],
        [
            "Start from the decision: Build only the detail that decision needs. A full monthly model is not automatically better.",
            "Link the statements: Net income flows to retained earnings. Depreciation, working capital, capex, and debt explain why profit is not cash.",
            "Drive working capital: Receivables, payables, and inventory follow the user's days or a clearly labeled assumption. Do not plug cash to make the balance sheet balance without saying so.",
            "Keep debt honest: Interest and principal follow the terms the user provided. If terms are missing, leave a labeled placeholder.",
            "Balance check: Assets equal liabilities and equity, or you show the plug and refuse to hide it.",
            "Document assumptions: A short list a reviewer can challenge. No circular story about growth funding itself unless the user describes that mechanism.",
        ],
        [
            "A P&L with a cash line typed in by hand and called a model.",
            "Hidden plugs.",
            "Invented debt terms.",
        ],
        "An operator wants a 12-month view that shows why a profitable year can still run out of cash.",
        "A linked sketch where the cash gap is explained by receivables and capex, with every assumption labeled and no hidden plug.",
        ["cash-flow-forecast", "working-capital", "financial-close-checklist"],
    ),
    skill(
        "working-capital",
        "Working Capital Review",
        "Find cash trapped in receivables, inventory, or payables, and separate a process fix from a one-time release.",
        "working-capital review",
        ["working capital", "cash conversion", "DSO DIO DPO", "cash trapped in the balance sheet"],
        ["Receivables, inventory, and payables balances", "Related revenue or cost, so days can be calculated", "Known disputes or obsolete stock", "Payment terms the user actually offers"],
        [
            "Compute days only if the bases exist: Do not invent DSO. Show the formula you used.",
            "Separate structural from overdue: Terms the company chose are not the same as customers paying late.",
            "Look at concentration: A few old invoices or SKUs often hold the cash. Ask for the aging if it was not provided, and do not pretend you saw it.",
            "Recommend a release that is real: Collections on disputed invoices are not a plan. Name what must be resolved first.",
            "Watch the rebound: A one-time collection is not a new run-rate. Say whether the improvement persists.",
            "Avoid squeezing suppliers blindly: Extending payables has a relationship and supply cost. State it.",
        ],
        [
            "A days metric with no formula.",
            "Counting disputed receivables as cash you will collect next week.",
            "A supplier stretch with no service risk.",
        ],
        "Cash is tight even though the company is profitable, and receivables grew faster than sales.",
        "A review that calculates days from the user's bases, flags concentration if known, and separates a one-time release from a process change.",
        ["cash-flow-forecast", "accounts-receivable-control", "inventory-policy"],
    ),
    skill(
        "capex-business-case",
        "Capex Business Case",
        "Write a capital-spend case that states the problem, the alternatives, and the cash consequences without fake precision.",
        "capex business case",
        ["capex case", "capital request", "should we buy this equipment", "investment business case"],
        ["The problem the spend solves", "Cost and timing the user has", "Alternatives including do nothing", "How benefits will be observed"],
        [
            "Define the problem: Downtime, capacity, safety, or compliance. A request that starts with the vendor's name is not ready.",
            "Compare alternatives: Buy, lease, outsource, or defer. Include do nothing and its operational cost if the user described one.",
            "Lay out cash: Deposit, install, training, and maintenance. Benefits are cash or a clearly non-cash obligation the user names, such as a safety requirement.",
            "Avoid theatrical IRR: If the user wants a return metric, compute it only from their cash items and show the sensitivity. Do not invent a hurdle rate.",
            "Name the benefit owner: Who will confirm, after installation, that the benefit showed up.",
            "State the kill: What finding during procurement would stop the spend.",
        ],
        [
            "A vendor quote pasted into a memo with no alternative.",
            "An IRR built on imagined savings.",
            "Ignoring training and downtime during install.",
        ],
        "Operations wants a packaging machine and has one quote and a claim that it will 'pay for itself'.",
        "A case with alternatives, cash timing, a benefit the team can later observe, and no invented hurdle rate.",
        ["investment-memo", "break-even-analysis", "production-schedule"],
    ),
    skill(
        "cost-reduction-sprint",
        "Cost Reduction Sprint",
        "Find cost that can come out without pretending that every cut is free of service impact.",
        "cost reduction sprint plan",
        ["cut costs", "cost reduction", "save money quickly", "expense sprint"],
        ["Cost baseline by category", "What must not be cut, in the user's words", "Contracts and notice periods if known", "Service or quality lines they will not cross"],
        [
            "Set a target and a boundary: How much, by when, and what is protected. A sprint without a protected list damages the business at random.",
            "Sort actions: Stop, renegotiate, delay, and redesign. Quick stops are not the same as structural redesigns.",
            "Estimate savings from the baseline: Use the user's numbers. Mark one-time savings separately from run-rate.",
            "Name the harm: Each material cut gets a service, risk, or morale consequence. If the user does not know it, list it as unknown rather than as zero.",
            "Assign owners and dates: A list without owners is a mood.",
            "Install a check: A short review two cycles later to see if the cost returned under another name.",
        ],
        [
            "Across-the-board percentage cuts with no owner.",
            "Counting a delayed project as permanent savings.",
            "Cutting a protected safety or compliance cost the user said was off limits.",
        ],
        "A company needs to remove a stated monthly amount within 60 days and has already ruled out layoffs.",
        "A sprint list of stops and renegotiations, run-rate versus one-time savings, and the service risk on each item.",
        ["budget-variance-review", "vendor-ops-review", "zero-based-budget-review"],
    ),
    skill(
        "revenue-recognition-review",
        "Revenue Recognition Review",
        "Prepare questions and a fact pattern for a revenue-recognition issue without pretending to issue an accounting opinion.",
        "revenue recognition fact pattern",
        ["revenue recognition", "can we book this revenue", "deferred revenue question", "contract accounting question"],
        ["The contract facts the user can share", "What was delivered and what was billed", "The framework the company claims to use", "The decision they need from finance or the auditor"],
        [
            "Write the fact pattern: Parties, promises, price, delivery, and acceptance, in the user's words. Do not upgrade vague facts into certainty.",
            "Separate billing from revenue: Cash collected and revenue recognized are different questions. Keep them apart.",
            "Identify the judgment: What is actually in dispute: number of promises, timing, or variable price. One sentence.",
            "List questions for the policy owner: What the accountant or auditor must answer. Do not answer GAAP or IFRS questions from memory as if they were rulings.",
            "Flag the management pressure: If the user wants a number in this period, note that the timing desire is not evidence.",
            "Hand off: Recommend the internal accounting owner. This skill does not close the books.",
        ],
        [
            "Declaring that revenue 'can be recognized' as a final opinion.",
            "Inventing a standard paragraph number.",
            "Letting a sales target decide the accounting.",
        ],
        "Sales wants a multi-year contract fully booked this quarter because the customer signed, but implementation has not started.",
        "A fact pattern that separates signing, billing, and delivery, plus questions for the accounting owner rather than a homemade ruling.",
        ["journal-entry-review", "financial-close-checklist", "contract-risk-review"],
        ["Issuing an audit opinion"],
    ),
    skill(
        "management-reporting-pack",
        "Management Reporting Pack",
        "Design a short monthly pack that tells leaders what changed, what it means, and what decision is due.",
        "management reporting pack outline",
        ["monthly pack", "management report", "board finance pack", "FP&A pack"],
        ["Who reads it", "Decisions the pack should trigger", "Numbers the team can produce reliably", "What is currently ignored in the old pack"],
        [
            "Choose the reader: A pack for the CEO is not a pack for every cost-center manager. Say which one you are designing.",
            "Lead with changes: Page one is cash, outlook versus plan, and exceptions. Activity belongs later or nowhere.",
            "Limit the pages: Recommend a handful of pages. Every chart needs a sentence that says so-what.",
            "Define sources: Each number has an owner and a close date. A pack that depends on heroic spreadsheets will be late or wrong.",
            "Add a decision log: Items needing a decision this month, not a gallery of KPIs.",
            "Retire pages: Name pages from the old pack to drop. Addition without subtraction is how packs become novels.",
        ],
        [
            "A 40-page pack with no ask.",
            "Charts with no source and no sentence.",
            "Different numbers for the same metric in two sections.",
        ],
        "The CEO stopped reading the monthly pack because it arrives late and repeats the chart dump.",
        "A short pack outline with page-one exceptions, source owners, and the old pages to retire.",
        ["budget-variance-review", "kpi-tree-finance", "executive-one-pager"],
    ),
    skill(
        "kpi-tree-finance",
        "Finance KPI Tree",
        "Break a financial outcome into drivers the operator can influence, and stop at metrics someone owns.",
        "finance KPI tree",
        ["KPI tree", "driver tree", "what drives margin", "finance metrics tree"],
        ["The top outcome", "The operating levers the team controls", "Metrics they can actually extract", "Owners"],
        [
            "Start at the outcome: Cash, contribution, or revenue quality. One top node.",
            "Decompose mathematically: Each level should explain the level above. If a metric does not connect, cut it.",
            "Stop at ownership: A driver with no owner is a decoration. Name the owner or stop decomposing.",
            "Mark leading versus lagging: The tree should show what the team can see before the month closes.",
            "Note data gaps: A missing driver is a measurement task, not a fake number.",
            "Tie to the scorecard: Recommend which nodes appear weekly and which appear monthly.",
        ],
        [
            "A mind map of every metric the company has ever tracked.",
            "Drivers that do not add up to the parent.",
            "No owners.",
        ],
        "A COO wants to know which weekly numbers explain monthly gross margin.",
        "A tree from gross margin to a few owned drivers, with data gaps called out and a weekly subset named.",
        ["north-star-metric", "management-reporting-pack", "metric-definition"],
    ),
    skill(
        "debt-capacity-screen",
        "Debt Capacity Screen",
        "Screen whether a borrowing idea fits the user's cash generation, without acting as a lender.",
        "debt capacity screen",
        ["can we borrow", "debt capacity", "loan versus equity", "covenant headroom"],
        ["Historical and expected cash generation the user provided", "Existing debt and covenants if known", "The use of the new money", "Security or guarantee constraints"],
        [
            "State the use: Borrowing for a defined need is different from borrowing because it is available. If the use is vague, say so.",
            "Look at coverage with their numbers: Show cash after maintenance needs versus proposed debt service. Do not invent a bank's credit box.",
            "Include existing promises: Covenants and liens the user already has come first. If unknown, the screen is incomplete.",
            "Compare with equity or delay: A screen that only cheers for debt is incomplete.",
            "Name the questions a lender will ask: Evidence, not a predicted approval.",
            "Do not request banking passwords or move money: This is a paper screen.",
        ],
        [
            "Promising that a bank will say yes.",
            "Ignoring existing covenants because they were not in the teaser.",
            "A debt recommendation for an undefined use.",
        ],
        "A company wants a term loan to fund a fit-out and has an existing facility with covenants they only partly remember.",
        "A screen that shows service versus their cash, flags the missing covenant facts, and does not predict an approval.",
        ["fundraising-model", "capex-business-case", "cash-flow-forecast"],
    ),
    skill(
        "fx-exposure-review",
        "Foreign Exchange Exposure Review",
        "Identify where currency actually hits cash, and separate a hedge policy question from a bookkeeping curiosity.",
        "FX exposure review",
        ["FX exposure", "currency risk", "hedging review", "exchange rate impact"],
        ["Currencies of revenue, costs, and cash", "Which exposures are contractual", "The user's hedge policy, if any", "The decision they need to make"],
        [
            "Map cash exposures: Where currency hits a bank account, not only where a report is translated.",
            "Separate transaction from translation: Management action usually belongs on contracted cash flows. Say which one the user is looking at.",
            "Quantify only with their data: A rate move they specify, applied to exposures they listed. Do not invent a forecast rate and call it the market.",
            "Policy before trades: If they have no hedge policy, recommend writing the policy questions, not a trade ticket.",
            "Note operational natural hedges: Costs in the same currency as revenue may already offset. Do not propose a hedge that doubles the risk.",
            "Hand off execution: This skill does not place trades or ask for brokerage logins.",
        ],
        [
            "Treating accounting translation as cash risk without checking.",
            "Inventing a hedge product and telling them to buy it.",
            "Asking for trading credentials.",
        ],
        "A firm invoices in euros and pays staff in dollars and wants to know if last month's margin drop was FX.",
        "A map of contractual cash exposure, a translation-versus-transaction split, and policy questions rather than a trade order.",
        ["pricing-margin-bridge", "cash-flow-forecast", "treasury-policy-brief"],
    ),
    skill(
        "financial-close-checklist",
        "Financial Close Checklist",
        "Tighten a monthly close so the numbers arrive once, with owners, and with fewer heroic journals.",
        "close checklist",
        ["month-end close", "financial close", "close checklist", "why is the close late"],
        ["Current close calendar", "Late or repeated tasks", "Systems involved", "Who signs off"],
        [
            "Map day zero to sign-off: List tasks in order, with the predecessor each task waits on.",
            "Assign one owner: A task owned by a team is a task that slips. Name a person the user identifies, or mark owner unknown.",
            "Move work before day one: Recurring reconciliations that can start earlier should. Say which ones.",
            "Define materiality for journals: Not every difference deserves an entry. Use the user's threshold or propose one as a proposal.",
            "Add a flux review: A short review of movements before sign-off, aimed at surprises, not at reprinting the ledger.",
            "Measure the close: Days to sign-off and number of post-close fixes. Improving the close is an operations problem.",
        ],
        [
            "A checklist copied from a generic calendar that ignores their systems.",
            "Sign-off with no flux review.",
            "Heroic journals every month treated as normal.",
        ],
        "The close takes 15 business days and three reconciliations always land on the last afternoon.",
        "A sequenced checklist, earlier starts for the late reconciliations, and two measures of close health.",
        ["month-end-close", "journal-entry-review", "management-reporting-pack"],
    ),
    skill(
        "forecast-accuracy",
        "Forecast Accuracy Review",
        "Measure how forecasts missed, separate bias from noise, and change the forecasting habit rather than the template.",
        "forecast accuracy review",
        ["forecast accuracy", "why is the forecast always wrong", "forecast bias", "prediction error"],
        ["Prior forecasts and actuals", "The grain: week, month, product, or team", "Known one-off events", "Who owns the forecast"],
        [
            "Choose the grain: Accuracy at the company level can hide a biased team. Use the grain the decision needs.",
            "Measure error and bias: Direction matters. A forecast that is always high is a different problem from one that jumps around.",
            "Exclude explained one-offs only if the user identifies them: Do not scrub the record to make the team look better.",
            "Find the habit: Sandbagging, hockey sticks, or ignored pipeline. Recommend one habit change.",
            "Do not add a new model first: If the inputs are political, a fancier model will be political too.",
            "Set a review: Compare the next two cycles to this baseline and stop there.",
        ],
        [
            "A single MAPE number with no bias view.",
            "Deleting inconvenient misses.",
            "Buying software before fixing the habit.",
        ],
        "Revenue forecasts have been high four months in a row and the team wants a new tool.",
        "An accuracy review that shows the directional bias, names the habit, and delays a tooling recommendation until the habit changes.",
        ["budget-variance-review", "demand-plan-review", "pipeline-review"],
    ),
    skill(
        "investment-memo",
        "Internal Investment Memo",
        "Write an internal memo for spending scarce cash on a bet, with the downside written in the same size font as the upside.",
        "internal investment memo",
        ["investment memo", "should we fund this bet", "internal investment paper", "resource bet memo"],
        ["The bet", "Cash and people required", "Evidence already in hand", "What failure looks like"],
        [
            "State the bet: Customer, offer, and the result that would make this a success, in the user's terms.",
            "Show evidence and gaps: What has been seen, and what is still a hope. Do not promote hope to evidence.",
            "Cost the full load: People, cash, and the work that will be delayed. Opportunity cost is part of the price.",
            "Write the downside: The likely way it fails and the cash already spent by then. Include a stop rule.",
            "Recommend fund, stage, or decline: Staging is the default when evidence is thin.",
            "Keep valuation language out unless the user is pricing an external instrument: This is an internal allocation memo, not a stock tip.",
        ],
        [
            "A pitch that only has an upside case.",
            "Ignoring the projects the bet will delay.",
            "Dressing an internal spend as if it were a public-market recommendation.",
        ],
        "A product leader wants headcount for a new segment and has three design-partner conversations, none paid.",
        "A memo that calls the conversations evidence of interest, not of demand, and stages spend behind a paid pilot.",
        ["capex-business-case", "ma-screening", "experiment-design"],
    ),
    skill(
        "saas-metrics-pack",
        "SaaS Metrics Pack",
        "Define a small SaaS metrics pack from the company's own billing reality, without imported benchmark theater.",
        "SaaS metrics definitions",
        ["SaaS metrics", "ARR MRR churn", "net revenue retention", "magic number"],
        ["How customers are billed", "Expansion, contraction, and churn definitions they want to use", "Segments that should not be mixed", "The decision the pack supports"],
        [
            "Define ARR or MRR from contracts: Write the inclusion rule. One-time services do not become ARR because someone wishes they would.",
            "Define retention carefully: Logo churn and revenue retention answer different questions. Do not blend them into one cheerful number.",
            "Segment if the motion differs: A self-serve cohort and an enterprise cohort do not share one retention story unless the user shows they do.",
            "Show the bridge: Starting recurring revenue, new, expansion, contraction, churn, ending. A single ending balance is not a pack.",
            "Skip vanity multiples: Do not compute a metric the billing data cannot support. Say it is unavailable.",
            "Refuse borrowed benchmarks: You may explain what a metric means. Do not declare the company healthy because a blog once named a number.",
        ],
        [
            "Calling services revenue ARR.",
            "One churn number for two different motions.",
            "A benchmark comparison invented from memory.",
        ],
        "A finance lead wants a board slide for net retention, but implementation fees have been folded into ARR.",
        "Definitions that pull fees back out, a revenue bridge, and no invented benchmark grade.",
        ["unit-economics", "management-reporting-pack", "metric-definition"],
    ),
    skill(
        "break-even-analysis",
        "Break-Even Analysis",
        "Find the volume or price where a defined contribution covers a defined fixed cost, and show the assumption that matters.",
        "break-even note",
        ["break even", "breakeven", "how many do we need to sell", "contribution versus fixed cost"],
        ["Price and variable cost per unit", "Which costs are fixed over the horizon", "The horizon", "Capacity limits"],
        [
            "Define the box: The product or location, and the months the fixed cost stays fixed. Break-even without a box is a slogan.",
            "Compute contribution per unit: Price minus variable cost, using the user's figures. If contribution is zero or negative, say break-even does not exist at this price.",
            "Divide fixed cost by contribution: Show the units and the revenue. Round only at the end, and say you rounded.",
            "Apply capacity: If the break-even volume exceeds capacity, the answer is that the cost structure does not fit, not a pep talk.",
            "Sensitivity: The variable that moves the answer most. One chart's worth of prose is enough.",
            "Do not add a profit goal silently: If the user wants a target profit, show it as a separate line.",
        ],
        [
            "Treating all costs as variable.",
            "Ignoring a capacity ceiling.",
            "A break-even point with no time box.",
        ],
        "A cafe owner wants to know how many days of a new catering offer it takes to cover a hired cook.",
        "A break-even quantity inside a stated time box, with the capacity check and the dominant assumption labeled.",
        ["unit-economics", "pricing-margin-bridge", "capex-business-case"],
    ),
    skill(
        "sensitivity-and-scenarios",
        "Sensitivity and Scenarios",
        "Show how a model moves when a few inputs move, without pretending the spreadsheet is a crystal ball.",
        "sensitivity note",
        ["sensitivity analysis", "what if this input changes", "tornado chart", "scenario versus sensitivity"],
        ["The model outcome that matters", "The inputs the user can actually vary", "A base case from their numbers", "The range they consider plausible"],
        [
            "Pick the outcome: Cash, margin, or runway. One outcome per pass.",
            "Vary one input at a time first: That is a sensitivity. Combinations are scenarios and should be named, not hidden in a data table.",
            "Use their ranges: Do not widen a range to make a picture look dramatic.",
            "Rank the drivers: Which input moves the outcome most across the stated range.",
            "Tell them what not to precise: If the top driver is a guess, more decimal places will not help.",
            "Recommend a measurement: The useful next step is often to learn the top driver, not to add more tabs.",
        ],
        [
            "A tornado built from invented ranges.",
            "Calling a one-way table a scenario plan.",
            "False precision.",
        ],
        "A launch model depends on conversion and fulfillment cost, and the team is arguing about formatting rather than drivers.",
        "A one-way sensitivity on the user's ranges, the dominant driver, and a recommendation to measure that driver before adding detail.",
        ["scenario-planning", "forecast-accuracy", "three-statement-model"],
    ),
    skill(
        "zero-based-budget-review",
        "Zero-Based Budget Review",
        "Rebuild a cost pool from activities that still earn their keep, instead of last year plus a percent.",
        "zero-based review of one cost pool",
        ["zero based budget", "rebuild the budget", "justify this spend", "cost pool review"],
        ["The cost pool", "The activities it pays for", "Demand for those activities", "The decision rights"],
        [
            "Bound the pool: One pool, such as travel, contractors, or a function's non-payroll spend. A company-wide zero-base in one sitting is theater.",
            "List activities: What work the money buys. Vendors are not activities.",
            "Tie to demand: Which activities a current strategy bet still requires. Orphan activities are the candidates.",
            "Rebuild: Propose a keep, reduce, and stop list with amounts from the user's baseline.",
            "Check the service: Who will feel a stop. Include that in the recommendation.",
            "Leave a rhythm: When this pool is reviewed again, so it does not silently return to last-year-plus.",
        ],
        [
            "Last year plus five percent, renamed zero-based.",
            "Cutting a pool without naming the activity.",
            "A company-wide exercise with no decision rights.",
        ],
        "Travel spend is up and nobody can say which trips still match the sales motion.",
        "A keep, reduce, and stop list for travel activities, tied to the current motion, with the customer-facing trips protected if the user said they matter.",
        ["cost-reduction-sprint", "budget-variance-review", "annual-planning-cycle"],
    ),
    skill(
        "treasury-policy-brief",
        "Treasury Policy Brief",
        "Draft the questions and structure of a simple cash and risk policy for a small finance team.",
        "treasury policy brief",
        ["treasury policy", "cash policy", "who can move money", "investment of surplus cash"],
        ["Entities and bank relationships the user mentioned", "Who may approve payments today", "Surplus cash, if any", "Risks they have already hit"],
        [
            "Write the purpose: Safeguard cash, pay on time, and avoid surprises. Do not turn a small company policy into a bank manual.",
            "Approval matrix: Recommend they document who can approve which payment size. Use their current practice as the starting point and flag gaps.",
            "Account rules: Which accounts exist and why, in their description. Suggest fewer accounts if they described confusion, and explain why.",
            "Surplus cash: If they park cash, list policy questions: access, credit quality, and who decides. Do not recommend a product or a yield.",
            "Exceptions: How an emergency payment is approved and recorded the next day.",
            "Do not ask for logins: Policy work does not need passwords, tokens, or card numbers.",
        ],
        [
            "A hedge fund investment policy for a company with one operating account.",
            "Requesting banking credentials to 'set up the policy'.",
            "Promising a return on surplus cash.",
        ],
        "A controller wants a one-page cash policy after a duplicate payment slipped through.",
        "A policy brief with an approval matrix, an exception path, and no request for credentials or product pitches.",
        ["fx-exposure-review", "internal-controls-walkthrough", "cash-flow-forecast"],
    ),
]
