from schema import skill

DOMAIN = {
    "id": "accounting",
    "title": "Accounting",
    "summary": "Close, controls, reconciliations, and audit preparation. Not an audit opinion or tax advice.",
    "keywords": ["accounting", "close", "reconcile", "controls", "audit"],
}

SKILLS = [
    skill(
        "chart-of-accounts-design",
        "Chart of Accounts Design",
        "Design a chart of accounts people can code to, with enough detail to manage and not so much that nobody agrees.",
        "chart of accounts proposal",
        ["chart of accounts", "GL structure", "account coding", "too many accounts"],
        ["Entities and departments that must report", "Decisions the accounts must support", "Current pain: miscoding or useless detail", "External reporting framework they claim to use"],
        [
            "Start from decisions: Which margins, locations, or funding sources must be visible without a side spreadsheet.",
            "Separate posting accounts from reporting groups: People post to stable accounts. Reports roll them up. Do not make every report slice a new account.",
            "Write definitions: Each new or changed account gets a one-line definition and an example of what does not belong in it.",
            "Cap the depth: Recommend a department or class dimension instead of exploding the natural account list, when their system supports it. If you do not know the system, ask before redesigning.",
            "Plan the map: Old account to new account. Unmapped balances are how conversions fail.",
            "Name the owner: Someone approves new accounts. A chart without an owner decays in a quarter.",
        ],
        ["A hundred new accounts with no definitions.", "Redesigning the chart to match a blog diagram.", "No mapping from the old balances."],
        "A growing firm has 400 accounts and still cannot see gross margin by service line.",
        "A proposal that uses a dimension for service line, defines the accounts that change, and maps old balances forward.",
        ["management-accounting-pack", "journal-entry-review", "month-end-close"],
    ),
    skill(
        "month-end-close",
        "Month-End Close",
        "Run a practical month-end close that produces one set of numbers and a short list of judgments.",
        "month-end close pack",
        ["month-end close", "close the books", "close calendar", "soft close"],
        ["Period and entities", "Open reconciliations", "Known judgments", "Sign-off owner"],
        [
            "Freeze the checklist: Use their close list. Add a missing reconciliation only if a balance sheet account has no owner.",
            "Clear suspense: Items in suspense need a destination or a labeled open item. Do not leave a plug and call the period closed.",
            "Record judgments: Accruals, cut-off, and estimates get a note with the fact pattern and the person who accepted it.",
            "Flux before sign-off: Explain material movements in plain language. A journal without a flux story is not reviewed.",
            "Lock and list: After sign-off, list post-close entries separately. Quiet edits are how trust dies.",
            "Hand the pack to reporting: Close produces numbers. The management pack explains them. Do not mix the two jobs in one heroic afternoon if both are slipping.",
        ],
        ["Closing with an unreconciled cash account.", "Post-close journals with no log.", "A narrative that invents reasons for a variance."],
        "The controller wants a soft close by day six and cash is still unreconciled on day five.",
        "A close status that refuses sign-off on unreconciled cash, lists open judgments, and separates any late entries.",
        ["financial-close-checklist", "bank-reconciliation", "journal-entry-review"],
    ),
    skill(
        "accounts-payable-control",
        "Accounts Payable Control",
        "Tighten payables so the company pays the right vendor, once, with evidence.",
        "payables control review",
        ["accounts payable", "duplicate payment", "AP control", "vendor payments"],
        ["How invoices arrive", "Who can add a vendor", "Approval limits", "Recent duplicate or fraud scares, if any"],
        [
            "Map the path: Invoice, receipt of goods or services, approval, payment. Note where one person can do two of those steps.",
            "Vendor master: New vendors need evidence the user already requires, plus a second look. Do not ask for or store bank passwords. Do not invent a vendor's bank details.",
            "Three-way match where it fits: Purchase, receipt, and invoice. Where a match does not fit, say what alternative evidence they use.",
            "Duplicate test: Same vendor, similar amount, close dates. Recommend a review list, not an automatic accusation.",
            "Payment run: Who reviews the run before release, and how exceptions are logged.",
            "Keep evidence: What is retained and for how long, using their retention rule if they have one. Do not invent a legal retention period.",
        ],
        ["One person adds vendors and releases payments with no second look.", "Calling every duplicate-looking item fraud.", "Requesting banking passwords."],
        "Two similar invoices from the same supplier were paid last quarter.",
        "A control review that separates vendor setup from payment release and proposes a duplicate review list without accusing the supplier.",
        ["expense-policy", "internal-controls-walkthrough", "vendor-contract-playbook"],
    ),
    skill(
        "accounts-receivable-control",
        "Accounts Receivable Control",
        "Review receivables so the aging means something and cash collection is a process, not a hope.",
        "receivables control review",
        ["accounts receivable", "AR aging", "collections control", "unapplied cash"],
        ["Aging by customer", "Billing terms", "Unapplied cash", "Disputes the user knows about"],
        [
            "Tie the aging to the ledger: If the aging and the GL disagree, that is the first finding. Do not analyze a report that does not tie.",
            "Split the buckets: Current, overdue, disputed, and unapplied. A disputed invoice is not a collections script.",
            "Credit notes and cash application: Unapplied cash hides both problems and comfort. List it.",
            "Concentration: A few customers may dominate overdue. Name them only from the user's data.",
            "Write the action by bucket: Bill, call, resolve dispute, or reserve. Reserving is an accounting judgment for the policy owner, not a collection tactic.",
            "Do not harass: Draft a factual collections note if asked. No threats, no shame language, no fake legal deadlines.",
        ],
        ["An aging that does not tie to the ledger.", "Treating disputes as lazy customers.", "Threatening language in a collections note."],
        "The AR aging shows a large over-90 bucket, and cash sits unapplied in the same report.",
        "A review that reconciles the aging, separates disputes from overdue, and lists unapplied cash before anyone writes a chase note.",
        ["working-capital", "revenue-recognition-review", "bank-reconciliation"],
    ),
    skill(
        "bank-reconciliation",
        "Bank Reconciliation",
        "Reconcile book to bank and leave a list of items a human must clear, with no plugs.",
        "bank reconciliation",
        ["bank reconciliation", "book to bank", "unreconciled cash", "bank rec"],
        ["Statement ending balance and date", "Book balance for the same account", "Outstanding checks and deposits", "Items the user cannot explain"],
        [
            "Match the account and the date: A reconciliation of the wrong account or the wrong day is not a near miss. Stop and correct the frame.",
            "Compute the difference: Statement balance to book balance, then list outstanding items the user supplied. Show the remaining unexplained amount in the open.",
            "Classify leftovers: Timing, error, or unknown. Unknown is acceptable. A forced explanation is not.",
            "Look for duplicates and old items: Outstanding items older than the user's threshold need a decision, not another month of carry-forward.",
            "Propose entries only as drafts: The accountant posts. You do not declare the books updated.",
            "No credentials: Do not ask for online banking passwords or one-time codes. Work from exports the user chooses to share.",
        ],
        ["A plug labeled 'other' to force a zero.", "Asking for a bank password.", "Carrying year-old outstanding items with no comment."],
        "The operating account reconciliation has an unexplained difference and three deposits in transit older than a month.",
        "A reconciliation that shows the unexplained amount, classifies the old deposits as needing a decision, and does not plug the difference.",
        ["month-end-close", "treasury-policy-brief", "internal-controls-walkthrough"],
    ),
    skill(
        "accrual-policy",
        "Accrual Policy",
        "Draft a short accrual policy so estimates are consistent, documented, and reversed on purpose.",
        "accrual policy draft",
        ["accrual policy", "when do we accrue", "month-end accruals", "estimate policy"],
        ["Types of accruals they actually book", "Materiality", "Who approves estimates", "Reversal practice today"],
        [
            "List the real accruals: Payroll, bonuses, received-not-invoiced, and others they named. Do not add a textbook list they do not use.",
            "Set the threshold: Below materiality, a practical rule beats false precision. Use their number or propose one as a draft.",
            "Evidence: Each accrual names its source document or calculation. 'Management believes' is not a method.",
            "Reversals: State whether the accrual reverses next period automatically and who checks the reversal did not double-count an invoice.",
            "Changes in estimate: How a changed assumption is noted. Do not hide a target-driven change.",
            "Owner: The policy names the approver. This draft is not itself a policy until they adopt it.",
        ],
        ["A policy copied from a large public company.", "Accruals with no evidence standard.", "Target-driven estimates treated as normal."],
        "Bonus accruals are booked differently by two entities, and neither documents the driver.",
        "A short draft policy covering their actual accruals, evidence, reversal, and an approver, marked as a draft.",
        ["journal-entry-review", "month-end-close", "management-accounting-pack"],
    ),
    skill(
        "fixed-asset-register",
        "Fixed Asset Register",
        "Review a fixed-asset register so additions, disposals, and depreciation have an owner and a trail.",
        "fixed-asset register review",
        ["fixed asset register", "depreciation review", "asset disposal", "capital versus expense"],
        ["Register and GL balances", "Capitalization threshold", "Recent additions and disposals", "Useful lives they claim to use"],
        [
            "Tie the register to the GL: Gross cost, accumulated depreciation, and net book value. A register that does not tie is the finding.",
            "Test additions against the threshold: Items under the threshold that were capitalized, or over it that were expensed, get a question. Do not rewrite their policy from memory.",
            "Disposals: A disposed asset needs a date and a proceed or a statement that proceeds were zero. Ghost assets still depreciating are a finding.",
            "Lives and methods: Flag inconsistencies inside their stated policy. Do not impose a new life because it 'feels standard'.",
            "Physical existence: Recommend a sample check for assets the user says have gone missing. Do not invent a count.",
            "Draft adjustments: Propose, do not post. Label any fully depreciated asset still in use as a policy question, not as an error by itself.",
        ],
        ["Inventing useful lives.", "Ignoring a register that does not tie.", "Writing off assets with no user evidence."],
        "The register net book value does not match the GL, and several laptops are still depreciating after people left.",
        "A review that leads with the tie-out break, lists disposal questions, and proposes sample checks rather than silent write-offs.",
        ["capex-business-case", "month-end-close", "internal-controls-walkthrough"],
    ),
    skill(
        "inventory-accounting",
        "Inventory Accounting Review",
        "Review inventory accounting issues: cut-off, obsolescence, and the tie between the count and the ledger.",
        "inventory accounting review",
        ["inventory accounting", "stock valuation", "obsolescence", "inventory count tie-out"],
        ["Count and GL figures", "Costing method they use", "Slow or damaged stock they know about", "Cut-off concerns"],
        [
            "Tie count to GL: Quantity times their cost, rolled to the balance. Explain any difference as timing, cost layer, or unknown.",
            "Cut-off: Goods received or shipped around period end need a status. Do not assume title transferred.",
            "Obsolescence: Use their evidence of age, damage, or expired demand. A reserve without evidence is a plug. A zero reserve despite their evidence is a question.",
            "Costing method: Describe the method they say they use. Do not switch them to another method casually.",
            "Standard cost variances: If they use standards, variances need a disposition. Unreviewed variances are not inventory gospel.",
            "Hand off judgment: The reserve percentage is for the accounting owner. You prepare the fact pattern.",
        ],
        ["A reserve percentage copied from a textbook.", "Ignoring cut-off.", "Changing costing method as a formatting choice."],
        "A year-end count is short of the GL, and the warehouse says some goods were shipped but still in the system.",
        "A tie-out that isolates the shipped-not-relieved population and asks for cut-off evidence before anyone books a shrinkage number.",
        ["inventory-policy", "incoming-inspection", "month-end-close"],
    ),
    skill(
        "intercompany-reconcile",
        "Intercompany Reconciliation",
        "Reconcile balances and transactions between entities so the group is not adding numbers that do not eliminate.",
        "intercompany reconciliation",
        ["intercompany", "intercompany reconciliation", "elimination entries", "related party balances"],
        ["Entities involved", "Balances each side recorded", "In-transit items", "Who approves eliminations"],
        [
            "Match both sides: Entity A receivable against entity B payable, same period. One-sided balances are the work.",
            "Classify differences: In-transit cash, FX, timing of invoices, or a booking error. Use the user's currency facts. Do not invent rates.",
            "Profit in inventory: If they sell goods between entities, flag unrealized profit as a question for their policy. Do not compute a tax position.",
            "Draft the elimination: Show the eliminating lines as a proposal that references both sides.",
            "Aging of differences: Old intercompany differences are a control failure, not a rounding issue.",
            "Owner going forward: A monthly match, with a named preparer, beats an annual archaeology project.",
        ],
        ["Eliminating a one-sided balance with no counterparty.", "Inventing an FX rate.", "Leaving multi-year differences as 'timing'."],
        "Two subsidiaries disagree by a material amount on a management fee, and the group close is tomorrow.",
        "A both-sides match, a classification of the difference, and a draft elimination that does not force a missing counterparty into existence.",
        ["month-end-close", "journal-entry-review", "fx-exposure-review"],
    ),
    skill(
        "audit-prep-pbc",
        "Audit PBC Preparation",
        "Build a provided-by-client list that answers the auditor's request without dumping the entire file room.",
        "PBC list and evidence index",
        ["PBC list", "audit preparation", "auditor request", "provided by client"],
        ["The auditor's request list, if any", "Systems and owners", "Known difficult areas", "The period under audit"],
        [
            "Restate each request: What evidence answers it, who owns it, and the period it covers. A request you do not understand gets a clarifying question, not a random export.",
            "Prefer system reports: Name the report and the parameters. A spreadsheet recreation is a last resort and should be labeled.",
            "Tie-out notes: For key numbers, say which report ties to the trial balance. Auditors will ask anyway.",
            "Sensitive access: Provide exports, not shared logins. Do not hand over production credentials.",
            "Track status: Open, provided, and follow-up. A list without status is a wish.",
            "Flag judgment areas: Revenue, inventory, and estimates need the memo, not only the number. Do not write a fake memo that invents the auditor's conclusion.",
        ],
        ["Sending a login instead of an export.", "A data dump with no tie-out.", "Inventing an audit conclusion in the cover note."],
        "The external auditor asked for revenue samples and the team is about to export every invoice with no index.",
        "An indexed PBC with owners, report parameters, tie-out notes, and no shared passwords.",
        ["internal-controls-walkthrough", "revenue-recognition-review", "financial-close-checklist"],
    ),
    skill(
        "expense-policy",
        "Expense Policy Draft",
        "Draft a usable expense policy: what is allowed, who approves, and what evidence is required.",
        "expense policy draft",
        ["expense policy", "T&E policy", "employee expenses", "reimbursement rules"],
        ["Current pain: late claims, unclear limits, or abuse concerns", "Approval limits", "Categories they want covered", "Local rules they already know apply"],
        [
            "Write the purpose: Fair reimbursement of business spend, not a surveillance program.",
            "Define allowed and not allowed: Use categories they named. Where they are unsure, mark a decision for leadership rather than inventing a moral rule.",
            "Evidence: Receipt threshold, attendees for meals if they want that, and the business reason. Do not require excessive personal data.",
            "Approvals: Manager plus a second look above a limit they set. Self-approval is called out as a gap.",
            "Timing: How soon a claim is submitted and paid. A policy nobody can follow will be ignored.",
            "Exceptions: Who can approve an exception and how it is logged. Quiet exceptions become the real policy.",
        ],
        ["A punitive policy that reads like a trap.", "No exception path.", "Inventing tax deductibility rules."],
        "Managers are approving their own travel after the fact, and finance wants a one-page policy.",
        "A draft with limits, evidence, a ban on self-approval above a threshold, and a logged exception path. Tax treatment is left to their advisor.",
        ["accounts-payable-control", "gifts-and-entertainment", "payroll-accounting-review"],
    ),
    skill(
        "payroll-accounting-review",
        "Payroll Accounting Review",
        "Review the payroll journal path from the payroll register to the ledger, including accruals and remittances.",
        "payroll accounting review",
        ["payroll accounting", "payroll journal", "payroll accrual", "wage reconciliation"],
        ["Payroll register totals", "Ledger accounts used", "Remittances due", "Known off-cycle payments"],
        [
            "Tie the register to the journal: Gross pay, deductions, employer costs, and net pay. A difference is a finding, not a rounding story, unless they show the rounding.",
            "Liability accounts: Deductions and employer taxes should land in liabilities until remitted. Net pay sitting in an expense account is a mapping question.",
            "Accrual: Days worked but not paid at period end. Use their calendar. Do not invent a pay cycle.",
            "Off-cycle and manual payments: List them and ask whether they hit the same controls.",
            "Remittance calendar: What is due, without giving tax advice. The skill schedules their stated dues. It does not opine on tax law.",
            "Access: Recommend that the person who changes pay rates is not the only person who reviews the register. Do not ask for payroll-system passwords.",
        ],
        ["Inventing tax rates.", "Ignoring off-cycle payments.", "Asking for payroll logins."],
        "The payroll register and the wage expense account have not matched for two months.",
        "A tie-out of gross-to-journal, a mapping question on liabilities, and a control note on who reviews the register.",
        ["month-end-close", "accrual-policy", "internal-controls-walkthrough"],
    ),
    skill(
        "tax-calendar",
        "Tax Calendar",
        "Build an internal calendar of tax and filing dates the user already knows they must meet, with owners. Not tax advice.",
        "internal tax calendar",
        ["tax calendar", "filing calendar", "compliance dates", "when are filings due"],
        ["Jurisdictions they operate in, as they list them", "Filings they already know about", "Owners", "Last year's late items"],
        [
            "Use their list: Record filings they know they have. Do not invent a filing obligation or a statutory deadline from memory.",
            "Ask them to confirm dates: Where a date is uncertain, mark it unconfirmed rather than filling in a confident wrong day.",
            "Add preparation lead time: The internal due date is earlier than the external date so review can happen.",
            "Owner and reviewer: One prepares, another reviews. A calendar with no names will slip.",
            "Evidence: What is saved when a filing is submitted. No credentials in the calendar.",
            "Hand off advice: Unusual positions, nexus questions, and interpretations go to their tax advisor. Say that explicitly.",
        ],
        ["Inventing deadlines.", "Giving a tax opinion.", "Storing portal passwords in the calendar."],
        "A company added a second state and the controller wants a calendar, but is unsure which filings apply.",
        "A calendar of known filings, unconfirmed items marked as such, internal lead times, and a clear handoff to their tax advisor for the new state.",
        ["compliance-calendar", "payroll-accounting-review", "audit-prep-pbc"],
        ["Tax advice or invented statutory deadlines"],
    ),
    skill(
        "journal-entry-review",
        "Journal Entry Review",
        "Review manual journals for purpose, support, and unusual patterns without accusing anyone on a hunch.",
        "journal entry review",
        ["journal entry review", "manual journals", "unusual entries", "JE support"],
        ["Population of manual journals", "Materiality", "Who can post", "Known top-side entries"],
        [
            "Define the population: Manual versus system-generated, for the period. Do not review a sample and call it the population.",
            "Support test: Each sampled entry needs a purpose and a source. Missing support is the finding, even if the amount looks ordinary.",
            "Unusual items: Round numbers, late posting, entries to cash or revenue, and entries by people who rarely post. Unusual means 'review', not 'misconduct'.",
            "Top-side entries: Management adjustments need the estimate memo. A verbal reason is a gap.",
            "Segregation: Note if the preparer and poster are the same person for material entries, using their described process.",
            "Write questions, not charges: The output is a review list for the controller. Do not allege fraud.",
        ],
        ["Calling an unusual entry fraud.", "A sample described as a full review.", "No interest in support as long as the amount is small but over their threshold."],
        "Several round-dollar journals hit revenue on the last day of the quarter.",
        "A review list that flags those entries for support and purpose, without alleging misconduct.",
        ["internal-controls-walkthrough", "revenue-recognition-review", "month-end-close"],
    ),
    skill(
        "internal-controls-walkthrough",
        "Internal Controls Walkthrough",
        "Walk through one process and describe the control as it is actually performed, including where it can fail.",
        "control walkthrough note",
        ["control walkthrough", "internal controls", "SOX walkthrough", "process control review"],
        ["The process", "The risk they care about", "Who performs the control", "Evidence the control produces"],
        [
            "Name the risk: What could go wrong in money, compliance, or reporting terms. A control with no risk is a habit.",
            "Describe the as-is: Who does what, how often, and what evidence exists. Use the user's description. Do not draw a fantasy flowchart of best practice and call it their process.",
            "Find gaps: Missing evidence, self-review, or a control that happens after the transaction is already irreversible.",
            "Distinguish design and operation: You can comment on design from an interview. You cannot say the control operated all year unless they give you samples.",
            "Recommend one fix: Evidence, a second reviewer, or a system check. A list of twenty improvements will not land.",
            "No false assurance: This note is not a controls opinion and not a certification.",
        ],
        ["A best-practice narrative presented as their process.", "Claiming the control operated all year from one interview.", "A certification no one issued."],
        "The team says vendor payments are 'reviewed' but cannot show what the reviewer looks at.",
        "A walkthrough that states the risk, describes the review as undocumented, and recommends one evidence fix without claiming certification.",
        ["control-design", "accounts-payable-control", "sox-walkthrough"],
    ),
    skill(
        "management-accounting-pack",
        "Management Accounting Pack",
        "Turn the ledger into a decision view: margins, cost centers, and a reconciliation back to the books.",
        "management accounting pack",
        ["management accounts", "cost center reporting", "margin by line", "internal financials"],
        ["Ledger for the period", "Dimensions they have: team, product, location", "Allocations they currently use", "The decision the pack serves"],
        [
            "Reconcile to the ledger: Every management view ties to the GL in a bridge. Untied 'adjusted' numbers are labeled non-GAAP or internal, in their words, and still bridge.",
            "Choose the cut: Product, location, or customer. One primary cut. A second cut only if they use it to decide.",
            "Allocations: Describe the driver they use. If there is no driver, show the cost as unallocated rather than inventing a spread.",
            "Contribution before overhead: Show a view before allocations so managers can see what they influence.",
            "Commentary: Three movements that matter, with facts. No invented market color.",
            "Owner: Who refreshes the pack after close, and on which day.",
        ],
        ["A management P&L that does not bridge to the books.", "Allocations with a made-up driver.", "Ten cuts and no decision."],
        "Leaders want margin by service line, but half of delivery cost sits in a general pool.",
        "A pack that shows contribution before allocation, labels the pool as unallocated, and bridges to the ledger.",
        ["chart-of-accounts-design", "kpi-tree-finance", "budget-variance-review"],
    ),
    skill(
        "account-reconciliation-standard",
        "Account Reconciliation Standard",
        "Set a standard for balance-sheet reconciliations: purpose, frequency, evidence, and aging of open items.",
        "reconciliation standard",
        ["reconciliation standard", "balance sheet reconciliations", "rec policy", "account ownership"],
        ["Material balance-sheet accounts", "Current reconcilers", "How old open items get", "Reviewer"],
        [
            "Assign every material account: An account without an owner is unreconciled even if the balance looks quiet.",
            "Define a proper recon: Source, book balance, itemized difference, and age of each open item.",
            "Frequency: Cash monthly at minimum, other accounts on a risk basis they agree. Do not demand a daily recon of every accrual without a reason.",
            "Aging policy: Open items older than their threshold need a disposition plan, not a permanent home.",
            "Review: Preparer and reviewer are different people for material accounts.",
            "Storage: Where the evidence lives. Not in a personal inbox only, and not behind a shared password.",
        ],
        ["A policy that says 'reconcile everything daily'.", "Open items older than a year with no comment.", "Shared logins to the evidence folder."],
        "Several balance-sheet accounts have no named preparer, and cash recs live in one person's inbox.",
        "A standard that assigns owners, defines a proper recon, and moves evidence to a shared location without shared passwords.",
        ["bank-reconciliation", "month-end-close", "internal-controls-walkthrough"],
    ),
]
