from schema import skill

DOMAIN = {
    "id": "legal",
    "title": "Legal operations",
    "summary": "Drafts, checklists, and intake for counsel. Not legal advice and not a filing service.",
    "keywords": ["legal", "contracts", "privacy", "counsel", "compliance"],
}

SKILLS = [
    skill(
        "contract-risk-review",
        "Contract Risk Review",
        "Review a contract the user provides and list commercial risks for counsel, without declaring it enforceable.",
        "contract risk memo",
        ["review this contract", "contract risks", "redline issues", "vendor agreement review"],
        ["The contract text or a faithful summary the user pasted", "Which side the user is on", "The deal they think they are making", "Must-have points they already know"],
        [
            "Confirm the text: Review only language the user supplied. If a clause is missing from what they pasted, say you cannot see it. Do not invent a clause.",
            "State the deal: In plain language, what each side gives and gets, based on the text.",
            "Flag asymmetry: Renewal, termination, liability caps, indemnity, assignment, and unilateral change rights. Quote the short phrase you are reacting to.",
            "Separate legal from commercial: Mark issues a business owner can decide and issues that need qualified counsel in their jurisdiction.",
            "Do not declare enforceability: You do not say a clause is legal, illegal, or 'standard for the market' from memory.",
            "Propose questions, not fake redlines: Suggested questions and fallback positions the user can take to counsel. Do not present a redline as legally sufficient.",
        ],
        ["A fake 'this contract is fine' conclusion.", "Inventing market standard language.", "Helping conceal a term from the other side's required approver."],
        "A founder pasted a vendor SaaS agreement and wants to know what could hurt them before signing.",
        "A memo quoting specific clauses, separating business choices from counsel questions, with no enforceability opinion.",
        ["nda-triage", "vendor-contract-playbook", "outside-counsel-brief"],
        ["A request to hide terms from a counterparty", "A request for a formal legal opinion"],
    ),
    skill(
        "nda-triage",
        "NDA Triage",
        "Triage a non-disclosure agreement so the user knows what it covers, how long, and what counsel should still check.",
        "NDA triage note",
        ["review an NDA", "non-disclosure agreement", "mutual NDA", "confidentiality agreement"],
        ["The NDA text", "Who discloses what", "The purpose of the talks", "The user's non-negotiables, if any"],
        [
            "Identify direction: Mutual or one-way, and whether that matches who will actually share information.",
            "Purpose limit: What the recipient may do with the information, in the text's words.",
            "Duration and residuals: How long duties last, and whether residual-memory language is present. Quote it if it is.",
            "Exclusions: Standard exclusions only count if they appear in the text. Do not assume them.",
            "Awkward clauses: Non-solicit, IP assignment, or exclusive dealing hidden in an NDA are flagged as out of place for counsel.",
            "Recommend a path: Sign, ask counsel to review specific lines, or do not sign yet. This is a triage, not a clearance.",
        ],
        ["Assuming mutual exclusions that are not in the file.", "Ignoring a non-solicit buried in the NDA.", "Declaring the NDA safe for every jurisdiction."],
        "A partnership conversation came with a one-way NDA that also assigns IP improvements to the other side.",
        "A triage that flags the IP assignment as unexpected, quotes it, and sends that clause to counsel before signature.",
        ["contract-risk-review", "ip-ownership-checklist", "vendor-contract-playbook"],
    ),
    skill(
        "vendor-contract-playbook",
        "Vendor Contract Playbook",
        "Build a playbook of positions for a class of vendor contracts the company signs repeatedly.",
        "vendor contract playbook",
        ["contract playbook", "vendor paper positions", "fallback positions", "procurement legal playbook"],
        ["The contract type", "Positions the business already cares about", "Past concessions they regret", "Who may approve a fallback"],
        [
            "Limit the scope: One contract type, such as SaaS subscriptions or contractors. A playbook for all contracts is a shelf ornament.",
            "Write positions: Preferred, acceptable fallback, and walk-away, for a handful of clauses they actually negotiate.",
            "Business owner: Each position names who may accept the fallback. Legal operations drafts. The business owns the risk trade.",
            "Explain why: One sentence on the operational consequence, not a fake case citation.",
            "Leave jurisdiction blank where needed: Note that counsel must localize governing law and liability positions.",
            "No dark patterns: The playbook does not teach anyone to hide terms or to slip in rights the other side would not notice.",
        ],
        ["A 40-clause encyclopedia nobody will use.", "Invented case law.", "Fallback authority left with 'the team'."],
        "The company signs a similar SaaS order form every month and keeps conceding auto-renewal by accident.",
        "A short playbook with preferred and walk-away positions on renewal, liability, and data, plus a named approver for fallbacks.",
        ["contract-risk-review", "procurement-award-note", "data-processing-addendum"],
    ),
    skill(
        "employment-agreement-review",
        "Employment Agreement Review",
        "Prepare a fact-based review list for an employment agreement so counsel and HR can see IP, restrictions, and pay terms.",
        "employment agreement review list",
        ["employment agreement", "offer letter legal review", "non-compete review", "contractor versus employee agreement"],
        ["The agreement text", "The role and location the user stated", "Whether the person is an employee or contractor in their description", "Concerns HR already has"],
        [
            "Restate the relationship: Use the label in the document and the label the user used. If they conflict, flag the conflict. Do not reclassify the worker as a legal conclusion.",
            "Compensation: Base, variable, and conditions for variable pay, quoted from the text. Note discretion that makes a bonus unclear.",
            "IP and work product: What is assigned, and whether prior inventions are handled. Flag silence.",
            "Restrictions: Non-compete, non-solicit, and confidentiality, including duration and geography as written. Do not opine that a restriction is enforceable.",
            "Exit terms: Notice, garden leave, and equity treatment only if present. Missing equity terms are a question, not an assumption.",
            "Send to counsel: Local employment law questions are listed, not answered.",
        ],
        ["Declaring a non-compete void.", "Reclassifying a contractor as an employee as a legal ruling.", "Inventing statutory notice periods."],
        "An offer letter is silent on IP and includes a two-year non-compete with no geography.",
        "A review list quoting the non-compete, noting the missing IP clause, and handing enforceability to local counsel.",
        ["offer-letter-checklist", "ip-ownership-checklist", "handbook-policy-draft"],
    ),
    skill(
        "privacy-notice-draft",
        "Privacy Notice Draft",
        "Draft a plain-language privacy notice from the data practices the user describes, and mark every unknown.",
        "privacy notice draft",
        ["privacy notice", "privacy policy draft", "what we tell users about data", "cookie notice outline"],
        ["What data they collect, in their words", "Why they collect it", "Who they share it with", "Where the notice will appear"],
        [
            "Inventory practices first: A notice that describes practices they do not have is a new problem. Use only their inventory.",
            "Write plainly: Categories of data, purposes, sharing, retention if they know it, and how people can ask questions.",
            "Mark unknowns: If retention or a vendor list is missing, insert a visible placeholder, not a invented '90 days'.",
            "No fake legal bases: Do not assign a GDPR lawful basis or a state-law category unless their counsel already named it.",
            "Match the product: The notice should match the flow a person actually sees. Flag collection that the product team has not mentioned to users.",
            "Counsel review: Label the draft as not for publication until qualified privacy counsel reviews the jurisdictions they name.",
        ],
        ["A generic policy pasted over a product that works differently.", "Invented retention periods.", "Publishing instructions that skip counsel."],
        "A startup collects account email and product usage and wants a website privacy notice tomorrow.",
        "A plain draft covering only those categories, with retention left as a placeholder and a counsel-review banner.",
        ["data-processing-addendum", "privacy-impact-assessment", "privacy-by-design"],
    ),
    skill(
        "data-processing-addendum",
        "Data Processing Addendum Checklist",
        "Check a data-processing addendum against the processing the business actually does, for counsel to finish.",
        "DPA checklist",
        ["DPA review", "data processing addendum", "processor terms", "subprocessor list"],
        ["The DPA text", "Whether the user is customer or vendor", "Categories of data they say are in scope", "Subprocessors they already use"],
        [
            "Match roles: Controller and processor labels in the DPA versus how the user described the work. Flag conflicts. Do not resolve the legal role yourself.",
            "Scope: Categories of data and purposes in the DPA versus the real service. Extra scope is a finding.",
            "Subprocessors: Compare the DPA mechanism to the user's actual vendor list. Silence about a known subprocessor is a question.",
            "Breach notice: The clock and the recipient, as written. Do not call a clock 'compliant'.",
            "Deletion and return: What the text says happens at the end. If operations cannot perform it, say so.",
            "International terms: If transfer language is present, quote it and send it to counsel. Do not invent a transfer mechanism.",
        ],
        ["A compliance stamp on a DPA.", "Ignoring a subprocessor the user already named.", "Inventing Standard Contractual Clauses."],
        "A customer sent a DPA that forbids subprocessors, but the product uses a hosted email vendor.",
        "A checklist that flags the conflict between the ban and the known vendor, without calling either side compliant.",
        ["privacy-notice-draft", "vendor-security-review", "privacy-impact-assessment"],
    ),
    skill(
        "ip-ownership-checklist",
        "IP Ownership Checklist",
        "List who is supposed to own work product across employees, contractors, and vendors, based on documents the user has.",
        "IP ownership checklist",
        ["IP ownership", "who owns the code", "contractor IP", "work product assignment"],
        ["Roles involved", "Agreements they have signed, as described", "The work product at issue", "Any open-source components they mentioned"],
        [
            "Inventory the creators: Employees, contractors, agencies, and founders. Ownership follows documents, not assumptions about who paid.",
            "Match agreements: For each creator type, note whether the user has an assignment or only a handshake. A missing document is the finding.",
            "Scope of assignment: What the document says is assigned, including improvements and feedback, quoted briefly.",
            "Third-party code: If they mentioned open source or a vendor toolkit, flag license review. Do not declare a license compatible from memory.",
            "Gaps: Work done before an agreement, or by a friend, needs a cleanup question for counsel.",
            "No filings: This skill does not file trademarks or patents and does not estimate registrability.",
        ],
        ["Assuming payment equals ownership.", "A fake patentability opinion.", "Ignoring pre-incorporation work."],
        "A contractor built the first version before any agreement existed, and the company is raising money.",
        "A checklist that marks that work as an open ownership gap and lists the document counsel would need to review.",
        ["open-source-license-review", "employment-agreement-review", "trademark-clearance-prep"],
    ),
    skill(
        "trademark-clearance-prep",
        "Trademark Clearance Prep",
        "Prepare a clearance brief so counsel or a search firm can look up a name. Do not clear the name yourself.",
        "trademark clearance brief",
        ["trademark clearance", "can we use this name", "brand name check", "trademark search prep"],
        ["The proposed name and stylization", "Goods or services in the user's words", "Markets they will sell in", "Names they have already seen in the wild"],
        [
            "Describe the use: Word mark, logo, or both, and the goods or services in plain language.",
            "Collect lookalikes: Names the user has already found. Do not claim you searched a registry unless a tool in the conversation actually did, and even then do not call it legal clearance.",
            "List questions: Class of goods, confusingly similar marks, and domain or handle conflicts are questions for a search, not answers.",
            "Avoid false comfort: 'I do not see a problem' is not an allowed conclusion.",
            "Recommend the next professional step: A qualified search in the jurisdictions they named.",
            "Do not file: No filing instructions presented as complete, and no urgency tricks.",
        ],
        ["Clearing a name because a domain was available.", "Inventing trademark classes as if they were advice.", "Fake search results."],
        "A team wants to know if a product name is safe because the .com was open.",
        "A clearance brief that refuses to treat the open domain as clearance and lists what a professional search must cover.",
        ["corporate-narrative", "brand-voice-guide", "ip-ownership-checklist"],
    ),
    skill(
        "terms-of-service-outline",
        "Terms of Service Outline",
        "Outline customer terms from the product's actual behavior so counsel can draft, not the other way around.",
        "terms of service outline",
        ["terms of service", "customer terms outline", "SaaS terms", "user agreement outline"],
        ["What the customer buys", "How they accept terms", "Limits the product really has", "Support and uptime promises marketing already makes"],
        [
            "Describe the service: What a customer can and cannot do, from product facts. Do not copy a famous company's terms.",
            "Acceptance: Where the user says acceptance happens. If the product has no acceptance moment, flag that as a product gap.",
            "Promises: List uptime, support, or outcome claims marketing already makes. Terms that contradict the website are a finding.",
            "Customer duties: Acceptable use, accounts, and payment, in plain language. No hidden punitive clause the business did not ask for.",
            "Liability and termination: Note that counsel must draft these for the jurisdiction. Provide the commercial intent only.",
            "Banner the draft: Not for publication. Counsel writes the operative terms.",
        ],
        ["Pasting another company's terms.", "Contradicting a published marketing promise without saying so.", "Calling the outline a finished agreement."],
        "Marketing promises a 99.9 percent uptime on the homepage, and the product team has no status page or credit policy.",
        "An outline that flags the homepage promise as a term that counsel and product must either support or remove.",
        ["marketing-claims-review", "privacy-notice-draft", "vendor-contract-playbook"],
    ),
    skill(
        "dispute-intake",
        "Dispute Intake",
        "Organize the facts of a dispute for counsel, preserving what is known, unknown, and time-sensitive.",
        "dispute intake memo",
        ["dispute intake", "we may be sued", "contract dispute facts", "demand letter arrived"],
        ["What the other side claims", "The timeline the user knows", "Documents they have", "Any stated deadline"],
        [
            "Chronology: Dates and facts only. Label disputed facts as disputed. Do not pick a winner.",
            "Documents: List what exists and where. Do not tell anyone to destroy, hide, or alter records.",
            "Preservation: Recommend they keep relevant records and talk to counsel about a legal hold. Do not run a hold yourself as if you were counsel.",
            "Deadlines: Record only deadlines written in the document they received. Do not calculate a statute of limitations from memory.",
            "Business impact: Cash, customers, and operations, so counsel sees context.",
            "Tone: The memo is internal and calm. No threats to draft, no public posts, no admissions dressed up as apologies.",
        ],
        ["Advising anyone to delete evidence.", "Inventing a limitation period.", "A fiery response sent without counsel."],
        "A customer sent a demand letter with a response date, and the team is arguing about blame in chat.",
        "A chronology, a document list, a preservation reminder, and the written response date flagged for counsel.",
        ["legal-hold-notice", "outside-counsel-brief", "contract-risk-review"],
        ["Destroying or hiding evidence", "Drafting a deceptive response"],
    ),
    skill(
        "legal-hold-notice",
        "Legal Hold Notice Draft",
        "Draft a plain legal-hold notice for counsel to approve, telling people to preserve records without spoiling anything.",
        "legal hold notice draft",
        ["legal hold", "litigation hold notice", "preserve documents", "hold notice"],
        ["The matter name counsel is using", "Who may have relevant records", "Systems those people use", "The counsel approver"],
        [
            "Write for humans: What to preserve, in everyday examples such as email, chat, and files, based on systems the user named.",
            "Say why briefly: A matter exists and records must be kept. Do not speculate about guilt or strategy.",
            "Forbid destruction: Include a clear line that routine deletion of relevant records must pause. Do not include tips for concealing records.",
            "Name a contact: Questions go to the counsel contact the user provides, not to a hallway conversation.",
            "Acknowledge: Ask for a confirmation line counsel can track.",
            "Approval gate: The draft is not sent until the named counsel approves it.",
        ],
        ["A notice that argues the case.", "Instructions that help someone hide records.", "Sending the notice without counsel approval."],
        "Counsel asked operations to warn three teams to keep project email, and the current draft sounds like an accusation.",
        "A calm draft that lists the systems, requires preservation, and waits for counsel approval.",
        ["dispute-intake", "records-retention", "outside-counsel-brief"],
    ),
    skill(
        "policy-exception-log",
        "Policy Exception Log",
        "Record a policy exception so the company can see who accepted the risk and when it expires.",
        "policy exception record",
        ["policy exception", "risk acceptance", "exception log", "waiver of policy"],
        ["The policy", "The exception requested", "The business reason", "The proposed expiry"],
        [
            "State the rule and the break: What the policy requires and what the team wants to do instead.",
            "Reason: The business reason in specific terms. 'We are busy' is not enough unless they truly have no other reason, in which case say that.",
            "Risk: What bad outcome the policy was meant to prevent, in plain language.",
            "Compensating step: What they will do meanwhile, and how someone will check.",
            "Expiry and owner: An exception without an end date is a silent policy change. Name the acceptor.",
            "No retroactive cover: Do not backdate an exception to hide something that already happened. Record the real dates.",
        ],
        ["A permanent exception with no owner.", "Backdating.", "Logging an exception for conduct the user describes as deceptive."],
        "A team wants to skip a vendor security review for a tool they already bought.",
        "An exception record with the skipped step, a short compensating review, a real expiry, and no backdating.",
        ["security-exception", "policy-writer", "vendor-security-review"],
    ),
    skill(
        "board-resolution-draft",
        "Board Resolution Draft",
        "Draft resolution language from a decision the board is actually being asked to make, for counsel or the secretary to finalize.",
        "board resolution draft",
        ["board resolution", "written consent", "director resolution draft", "approve a resolution"],
        ["The exact decision", "The approving body", "Any recusal the user mentioned", "Supporting paper already prepared"],
        [
            "Use their decision: The resolution authorizes only what they described. Do not add broad powers for convenience.",
            "Identify the body: Board, committee, or shareholder, as the user stated. If they are unsure which body must approve, flag that for counsel instead of guessing.",
            "Recusals: If they named a conflict, the draft notes the recusal and does not count that person in favor.",
            "Authority: Who may sign documents after approval, by name or role they gave.",
            "Attachments: Refer to the memo or agreement by title. Do not invent a document date.",
            "Secretary review: Mark the draft unofficial until the corporate secretary or counsel accepts it.",
        ],
        ["A resolution that grants open-ended authority.", "Guessing the approving body.", "Ignoring a stated conflict."],
        "The board is asked to approve a bank account change, and one director works for the bank.",
        "A narrow draft authorizing the account change, noting the recusal, and waiting for the secretary.",
        ["board-memo-writer", "corporate-records-hygiene", "board-meeting-facilitator"],
    ),
    skill(
        "corporate-records-hygiene",
        "Corporate Records Hygiene",
        "Check whether basic corporate records are findable and consistent, without filing anything.",
        "corporate records checklist",
        ["corporate records", "cap table documents", "minute book", "entity records hygiene"],
        ["Entities they listed", "Records they can find", "Known gaps", "Upcoming transaction that needs the records"],
        [
            "List entities: Name, role, and formation place only as the user stated. Do not look up or invent registry data.",
            "Core set: Formation document, ownership records, and recent approvals they say exist. Missing items are gaps, not failures of memory to paper over.",
            "Consistency: Names and share counts that disagree across documents they described are findings.",
            "Access: Who can find the records on a sick day. A single laptop is a risk.",
            "No filings: Recommend counsel or a registered agent for any filing. Do not generate filing forms as if they were ready to submit.",
            "Transaction use: If a raise or sale is coming, highlight the gaps that will be asked for first.",
        ],
        ["Inventing incorporation dates.", "Preparing a filing and calling it ready.", "Ignoring a share-count mismatch."],
        "A financing is six weeks away and the founder cannot find signed founder stock documents.",
        "A gap list that prioritizes the missing stock documents and does not invent replacement signatures.",
        ["ip-ownership-checklist", "board-resolution-draft", "fundraising-model"],
    ),
    skill(
        "open-source-license-review",
        "Open-Source License Review",
        "Triage open-source components the user lists so engineering and counsel can see obligations. Not a compatibility ruling.",
        "open-source triage",
        ["open source license", "OSS review", "dependency license", "copyleft question"],
        ["The components and versions they listed", "How the component is used: linked, modified, or distributed", "The product's distribution model", "Licenses they already identified"],
        [
            "Use their inventory: Do not pretend to scan a codebase unless the user provided the scan output.",
            "Record the license name they supplied: If the license text is missing, say the triage cannot classify that component.",
            "Usage matters: A tool that runs in development is a different question from code distributed to customers. Use their description.",
            "Obligations in plain language: Attribution, source offer, or reciprocal terms only as those duties are commonly described, and mark them for counsel to confirm. Do not give a legal compatibility opinion.",
            "Flag unknowns: Custom forks and missing versions are stop points.",
            "No piracy help: This skill does not remove license notices or hide copied code.",
        ],
        ["A blanket 'all MIT, you are fine'.", "Helping strip license notices.", "Classifying a component with no license text."],
        "A release candidate includes a library the scan labels as a reciprocal license, and the team ships binaries to customers.",
        "A triage that isolates that component, states the usage, and sends the obligation question to counsel instead of clearing the release.",
        ["ip-ownership-checklist", "dependency-upgrade", "sbom-and-supply-chain"],
    ),
    skill(
        "marketing-claims-review",
        "Marketing Claims Review",
        "Review marketing claims for substantiation gaps before they are published.",
        "claims review note",
        ["marketing claims review", "can we say this", "substantiation", "advertising review"],
        ["The draft claim", "The evidence they have", "Where it will appear", "The product the claim describes"],
        [
            "Quote the claim: Review the words they will publish, not a softened retelling.",
            "Match evidence: Each factual claim needs a source they possess. If the source is missing, the claim is not ready.",
            "Watch absolutes: 'Only', 'guaranteed', 'never', and performance numbers are high risk if evidence is thin. Recommend narrower wording.",
            "Comparisons: Competitor comparisons need a fair basis they can show. Do not draft a comparison they cannot support.",
            "Testimonials: Do not invent quotes. If they want a customer story, the customer must approve the real words.",
            "Counsel for regulated claims: Health, safety, and financial-return claims are flagged, not cleared.",
        ],
        ["Inventing a statistic.", "Leaving 'guaranteed results' because it converts.", "Fake testimonials."],
        "A landing page says the product cuts costs by 40 percent, and the only support is one customer's anecdote.",
        "A review that blocks the percentage claim until evidence exists and offers narrower wording tied to that one story, clearly labeled.",
        ["customer-story", "terms-of-service-outline", "positioning-statement"],
    ),
    skill(
        "whistleblower-intake",
        "Whistleblower Intake",
        "Structure an internal report of misconduct so it can be handled fairly, without retaliation or a witch hunt.",
        "whistleblower intake note",
        ["whistleblower report", "ethics report", "internal misconduct report", "speak-up intake"],
        ["What was reported, with identifiers minimized", "Who received it", "Immediate safety concerns", "The company's stated process, if known"],
        [
            "Stabilize: If someone may be in danger, tell the user to use local emergency services and their safety process. Do not investigate a crime scene yourself.",
            "Record facts: What was alleged, when it was received, and what is still unknown. Do not add motive.",
            "Minimize data: Include names only as needed to route the report. Do not build a dossier for curiosity.",
            "No retaliation: Remind the handler that punishing the reporter is not an option you will help with.",
            "Route: Follow the company's stated channel. If none exists, recommend an independent reviewer rather than the accused person's chain of command.",
            "Preserve records: Keep the report. Do not draft a plan to delete it.",
        ],
        ["Helping retaliate against a reporter.", "A public accusation draft.", "Investigating by collecting unrelated personal data."],
        "An employee reported a possible bribe and the manager wants to know if they can quietly move the reporter off the account.",
        "An intake note that routes the allegation to an independent reviewer and refuses the retaliatory move.",
        ["ethics-hotline-triage", "dispute-intake", "employee-relations-intake"],
        ["Retaliation", "Covering up a report"],
    ),
    skill(
        "outside-counsel-brief",
        "Outside Counsel Brief",
        "Brief outside counsel with the question, the facts, and the business constraint, so the meter starts on the right problem.",
        "outside counsel brief",
        ["brief outside counsel", "lawyer brief", "counsel instructions", "legal question memo"],
        ["The decision needed", "The deadline", "Facts and documents", "The business constraint"],
        [
            "Ask one question: A brief that asks counsel to 'look at this' will return a seminar. Write the decision the company must make.",
            "Facts in order: Chronology, documents attached or listed, and unknowns. Do not hide a bad fact to get a comforting answer.",
            "Business constraint: Budget, launch date, or relationship risk, labeled as context, not as an instruction to reach a preferred legal answer.",
            "Prior advice: Note advice already received so counsel does not restart blindly.",
            "Privilege care: Mark the draft as a request for legal advice if the user says that is the intent. Do not claim privilege as a magic label on ordinary business notes.",
            "Desired deliverable: A short advice note, a markup, or a call. Say which.",
        ],
        ["Hiding an inconvenient fact.", "Asking for a predetermined answer.", "A brain dump with no question."],
        "The CEO wants counsel to review a partnership in three days and has sent a 40-page data room link with no question.",
        "A one-question brief, a chronology, the three-day deadline, and a requested short advice note.",
        ["contract-risk-review", "dispute-intake", "board-memo-writer"],
    ),
]
