from schema import skill

DOMAIN = {
    "id": "people",
    "title": "People and culture",
    "summary": "Hiring, performance, pay bands, and workplace processes that stay fair and specific. Not legal advice.",
    "keywords": ["hr", "hiring", "performance", "people", "culture"],
}

SKILLS = [
    skill(
        "job-description-writer",
        "Job Description Writer",
        "Write a job description from outcomes and constraints, not a wishlist of tools and years.",
        "job description",
        ["job description", "write a JD", "role profile", "hiring post"],
        ["Why the role exists now", "Outcomes for the first year", "Team and manager", "Location, level, and whether pay can be disclosed"],
        [
            "Purpose: One sentence a candidate can repeat, tied to the team's current need.",
            "Outcomes: Three to five first-year results. Tools support outcomes. They are not the job.",
            "Must-haves: Cap at five. A requirement the manager cannot defend as a predictor moves to nice-to-have.",
            "Context: Level, location, travel, and reporting line. Do not invent a salary. If pay is undisclosed, say so.",
            "Inclusive language: Remove jargon and requirements that narrow the pool without improving the work, and say what you removed.",
            "Process: How to apply and what the process involves, only if the user knows it. Do not invent a hiring promise.",
        ],
        ["A tool dump.", "Ten must-haves copied from a senior role onto a junior one.", "An invented salary range."],
        "A manager wants a senior analyst posting and sends a list of software products.",
        "A posting with first-year outcomes, five must-haves, and pay left undisclosed rather than invented.",
        ["structured-interview", "hiring-scorecard", "compensation-band"],
    ),
    skill(
        "structured-interview",
        "Structured Interview",
        "Design an interview that asks every candidate the same job-related questions and scores them the same way.",
        "structured interview kit",
        ["interview guide", "structured interview", "interview questions", "onsite plan"],
        ["The outcomes in the job description", "Interview length", "Interviewers and their lanes", "Legal constraints the user already stated"],
        [
            "Map questions to outcomes: Every question earns its place by predicting one outcome. Cut clever questions that do not.",
            "Write the look-fors: What a strong, mixed, and weak answer contains, so interviewers are not improvising taste.",
            "Assign lanes: Each interviewer owns different questions. Overlap is a waste of the candidate's time.",
            "Ban the irrelevant: No questions about family, health, age, or other personal status. If the user asks for those, refuse and explain why.",
            "Score independently: Interviewers score before the debrief. The debrief discusses evidence, not charisma.",
            "Candidate experience: Tell the candidate what will be covered and how long it takes. No trick assignments.",
        ],
        ["Unstructured 'tell me about yourself' as the whole process.", "Different questions for different candidates to fish for a favorite.", "Personal-status questions."],
        "Two interviewers want to 'just chat' with finalists for a role that has a written outcomes list.",
        "A kit with shared questions, look-fors, independent scoring, and no personal-status questions.",
        ["hiring-scorecard", "job-description-writer", "inclusive-hiring"],
    ),
    skill(
        "hiring-scorecard",
        "Hiring Scorecard",
        "Turn interview evidence into a hire, no-hire, or hold decision without a vibe vote.",
        "hiring scorecard",
        ["hiring scorecard", "debrief", "should we hire", "candidate decision"],
        ["The agreed criteria", "Evidence from each interviewer", "Concerns still open", "The decision owner"],
        [
            "Use the criteria already set: Do not add a new must-have in the debrief to justify a preference.",
            "Evidence over adjectives: 'Great communication' needs the example the interviewer heard. Adjectives alone do not score.",
            "Separate missing evidence from negative evidence: A short interview is not a failed answer.",
            "Name the risk: The main way this hire could fail in the first six months, and whether a reference or work sample would reduce it.",
            "Decide: Hire, no-hire, or hold for a specific missing fact. A hold needs a date.",
            "Document fairly: The note should be something the company could show a reviewer. No jokes about candidates.",
        ],
        ["A vote based on who clicked with the founder.", "Moving the criteria after meeting a favorite.", "Undocumented side-channel vetoes."],
        "The panel liked a candidate's energy but nobody tested the analysis outcome in the job description.",
        "A scorecard that marks that outcome untested and recommends a work sample instead of a hire.",
        ["structured-interview", "offer-letter-checklist", "inclusive-hiring"],
    ),
    skill(
        "offer-letter-checklist",
        "Offer Checklist",
        "Prepare an offer checklist so compensation, start date, and conditions are complete before anyone celebrates.",
        "offer checklist",
        ["offer letter", "prepare an offer", "offer checklist", "verbal offer"],
        ["Role and level", "Compensation parts the company intends", "Start date and contingencies", "Approver"],
        [
            "List the parts: Base, variable, equity if any, and benefits status. Do not invent numbers or equity values.",
            "Contingencies: Background, work authorization, or other checks only if the user says they are part of the process. Do not invent a check.",
            "Manager alignment: The hiring manager and the approver agree on level and pay band. If they do not, stop the checklist and surface the conflict.",
            "Candidate-facing clarity: What is guaranteed versus discretionary, in plain language.",
            "Expiration: An offer date and a response date the user chooses. Do not create false urgency.",
            "Counsel and HR own the letter: This skill checks completeness. It does not declare the letter legally sufficient.",
        ],
        ["A verbal offer that omits variable-pay conditions.", "Invented equity value.", "False exploding-offer pressure."],
        "A manager told a candidate a number on a call, and finance has not approved the band.",
        "A checklist that blocks the letter until the band is approved and lists the verbal number as not yet an offer.",
        ["compensation-band", "employment-agreement-review", "onboarding-plan"],
    ),
    skill(
        "onboarding-plan",
        "Onboarding Plan",
        "Plan a new hire's first weeks so they can do useful work without drinking from a firehose of links.",
        "onboarding plan",
        ["onboarding plan", "first week plan", "new hire ramp", "orientation plan"],
        ["Role outcomes", "Start date", "Tools and access they truly need", "The buddy or manager"],
        [
            "Week-one outcome: One useful piece of work, not a tour of every tool.",
            "Access list: Only the systems required for that work. Do not request or store passwords in the plan.",
            "People: Manager, buddy, and the three colleagues they will need. A 20-person meet-and-greet is optional, not the plan.",
            "Context pack: The strategy page, the team scorecard, and the glossary they actually use.",
            "Checkpoints: End of week one and end of week four, with questions the manager will ask.",
            "Feedback path: How the hire raises confusion early. Onboarding is a management duty, not only an HR calendar.",
        ],
        ["A link dump.", "No manager checkpoint.", "Passwords written into the plan."],
        "A new analyst starts Monday and the current plan is a folder of 40 documents.",
        "A four-week plan with one week-one deliverable, a short access list, and two manager checkpoints.",
        ["thirty-sixty-ninety", "job-description-writer", "learning-path"],
    ),
    skill(
        "thirty-sixty-ninety",
        "Thirty Sixty Ninety Plan",
        "Write a 30-60-90 plan that a new hire and their manager can both grade.",
        "30-60-90 plan",
        ["30-60-90", "ramp plan", "first 90 days", "new leader plan"],
        ["Role outcomes", "What the team most needs in the first quarter", "Known landmines", "How success will be judged"],
        [
            "30 days is learning and a small delivery: Relationships, system map, and one shipped contribution.",
            "60 days is independent work: The hire runs a defined slice without the manager in every step.",
            "90 days is a result: A measurable improvement or a decision the team needed. Not a list of meetings attended.",
            "Manager commitments: What the manager will provide: context, introductions, and feedback dates.",
            "Landmines: One or two risks the user named, and how the hire should treat them. No gossip section.",
            "Review dates: Put the three reviews on the calendar in the plan itself.",
        ],
        ["A 90-day plan that is only learning goals.", "No manager commitments.", "Unmeasurable 'build relationships' as the only 90-day result."],
        "A new team lead wants a 30-60-90 before day one, and the team has a late monthly close.",
        "A plan whose 90-day result is a close improvement the manager can observe, with review dates included.",
        ["onboarding-plan", "performance-review", "manager-one-on-one"],
    ),
    skill(
        "performance-review",
        "Performance Review",
        "Draft a performance review from evidence, with no surprise criteria and no empty praise.",
        "performance review draft",
        ["performance review", "write a review", "annual review", "review draft"],
        ["The goals that were actually set", "Evidence from the period", "The rating scale if one exists", "Development interest the employee stated"],
        [
            "Use the original goals: Do not grade people on expectations never shared. If goals were missing, say the review is starting from a gap.",
            "Evidence: Two or three specific examples for praise and for concern. No example, no strong claim.",
            "Impact: What the work changed for customers or colleagues, not how hard the person seemed to work.",
            "Development: One skill to grow, tied to upcoming work. A development list of ten items is a shrug.",
            "Tone: Direct and respectful. No jokes, no medical speculation, no comparison to unnamed peers.",
            "Manager owns it: The draft is for the manager to edit and deliver. You do not put words in the employee's mouth.",
        ],
        ["Surprise criteria.", "Praise with no example.", "A review that diagnoses a health or personality condition."],
        "A manager wants to rate someone low for 'attitude' but has not named a missed goal.",
        "A draft that refuses the attitude label, asks for examples against the original goals, and limits development to one skill.",
        ["pip-design", "manager-one-on-one", "thirty-sixty-ninety"],
    ),
    skill(
        "pip-design",
        "Performance Improvement Plan",
        "Design a fair, time-boxed improvement plan with observable standards, not a paper trail dressed up as coaching.",
        "performance improvement plan draft",
        ["PIP", "performance improvement plan", "underperformance plan", "improvement plan"],
        ["The gap, in observable terms", "Support already offered", "The standard for the role", "Duration and reviewer"],
        [
            "Describe the gap: What work is below the standard, with examples. 'Bad attitude' is not a standard.",
            "Confirm the standard was known: If it was not, the first step may be a clear expectation, not a PIP. Say so.",
            "Set a short list of observable targets: What done looks like, how it will be measured, and the review dates.",
            "Support: Training, examples, or workload changes the manager will actually provide.",
            "Consequences: Use only consequences the user says the company process allows. Do not invent a firing script or a legal conclusion.",
            "Dignity: The plan is private, specific, and free of humiliation. Refuse plans whose real aim is to force a resignation through impossible tasks.",
        ],
        ["Vague attitude goals.", "Impossible tasks designed to push someone out.", "Invented legal conclusions about termination."],
        "A manager wants a PIP because a teammate 'is not a culture fit' and cannot name a missed deliverable.",
        "A response that stops the PIP until an observable gap exists, and refuses a plan built to force a resignation.",
        ["performance-review", "employee-relations-intake", "manager-one-on-one"],
        ["A plan designed to force someone out", "Discriminatory targeting"],
    ),
    skill(
        "compensation-band",
        "Compensation Band Review",
        "Review a pay decision against the band and the evidence, without inventing market rates.",
        "compensation review note",
        ["pay band", "compensation review", "salary band", "offer versus band"],
        ["The band if they have one", "The proposed pay", "The evidence for the person's level", "Internal peers the user chooses to include"],
        [
            "Start with their band: If no band exists, say the decision is discretionary and do not invent market percentiles.",
            "Level evidence: Does the person's work match the level definition they provided. Pay does not define level after the fact.",
            "Internal consistency: Compare only with peers the user supplied. Do not guess what others are paid.",
            "Range placement: Where the proposal sits in the band, and what would justify an exception.",
            "Exception log: If they go outside the band, name the approver and the review date.",
            "No market theater: You may list questions for a compensation consultant. You do not fabricate a survey number.",
        ],
        ["Invented percentile data.", "A raise justified only by a competing anecdote with no band.", "Comparing to peers the user did not authorize you to discuss."],
        "A manager wants to beat a competitor's verbal offer and the proposal sits above the band.",
        "A note that places the proposal above the band, requires an approver, and does not invent a market percentile.",
        ["offer-letter-checklist", "total-rewards-brief", "workforce-plan"],
    ),
    skill(
        "engagement-survey-readout",
        "Engagement Survey Readout",
        "Turn survey results the user provides into a few actions, without over-reading small slices.",
        "survey readout",
        ["engagement survey", "survey readout", "employee survey results", "eNPS results"],
        ["The results they have", "Response rate and slice sizes", "Last cycle's actions", "What leadership can actually change"],
        [
            "Lead with response quality: A slice with a tiny response rate is a hint, not a verdict. Say so.",
            "Pick three movements: Up, down, or stuck, compared with their prior survey if they have one. No prior, no fake trend.",
            "Pair scores with comments only if comments were provided: Do not invent themes.",
            "Choose actions inside their power: One management habit and one system fix. A poster about values is not an action.",
            "Close the loop: What employees will be told, by when. Asking for feedback and going silent is the failure mode.",
            "Privacy: Do not identify a commenter from a small team. Aggregate or suppress.",
        ],
        ["Ranking managers from tiny samples.", "Identifying a commenter.", "A long list of actions nobody owns."],
        "A 12-person team had a low score and three comments, and a leader wants to name the complainer.",
        "A readout that refuses identification, treats the sample carefully, and proposes one owned action plus a close-the-loop message.",
        ["stay-interview", "culture-diagnostic", "manager-one-on-one"],
    ),
    skill(
        "stay-interview",
        "Stay Interview",
        "Prepare a stay conversation that asks what would keep a person, without turning it into surveillance or a promise.",
        "stay interview guide",
        ["stay interview", "retention conversation", "why might they leave", "keep this person"],
        ["The person's role", "What the manager can actually change", "Known flight risks the user may share", "Promises already made"],
        [
            "Purpose: Learn what helps this person do their best work and what might push them out. It is voluntary.",
            "Questions: A few open questions about the work, the manager, and growth. No trick questions. No asking friends' opinions.",
            "Authority: The manager notes what they can change and what they cannot. Do not script a promise of promotion or pay they cannot keep.",
            "Listen for themes: Workload, recognition, growth, or manager behavior. Do not diagnose personal lives.",
            "Follow-up: One action the manager will take, and one they will explicitly not pretend to take.",
            "Privacy: The notes are for the manager and HR if the user says that is the process. Not for a rumor file.",
        ],
        ["A stay interview that is really an interrogation.", "Fake promotion promises.", "Collecting personal family details."],
        "A manager heard a star performer is interviewing and wants a script that promises a new title.",
        "A guide that asks useful questions and forbids a title promise the manager has not had approved.",
        ["engagement-survey-readout", "compensation-band", "manager-one-on-one"],
    ),
    skill(
        "offboarding-checklist",
        "Offboarding Checklist",
        "Plan a respectful departure: access, knowledge, equipment, and a clean final pay question list.",
        "offboarding checklist",
        ["offboarding", "employee exit", "leaver checklist", "termination logistics"],
        ["Last day", "Role and critical knowledge", "Systems the user says they can access", "Whether the exit is voluntary, as stated"],
        [
            "Knowledge: What must be handed over before the last day, and to whom. A password share is not a handover. Reset access instead.",
            "Access: List systems to remove on a schedule the user controls. Do not include instructions for locking someone out in a harmful or deceptive way.",
            "Equipment and accounts: Company devices and accounts. Personal data is handled according to their policy, not by rummaging.",
            "Final pay and benefits: Questions for payroll, not answers invented from labor law.",
            "Exit conversation: A respectful outline. No gotcha interview. No request to badmouth the person to the remaining team.",
            "Customer continuity: Who owns live work. Customers should not discover the gap themselves.",
        ],
        ["Sharing passwords as the handover.", "A gossip script for the remaining team.", "Invented final-pay law."],
        "A specialist with sole access to a billing tool is leaving in ten days.",
        "A checklist that transfers knowledge, schedules access removal without password sharing, and names the customer owner.",
        ["onboarding-plan", "employee-relations-intake", "knowledge-base-article"],
    ),
    skill(
        "org-design-review",
        "Org Design Review",
        "Review a proposed org change against the work that must happen, not against a fashionable span-of-control number.",
        "org design review",
        ["org design", "restructure", "span of control", "team structure"],
        ["The work the organization must do", "The proposed structure", "Known single points of failure", "What problem the redesign is meant to solve"],
        [
            "Start with the problem: Slow decisions, unclear ownership, or a new strategy. A redraw with no problem will create a new one.",
            "Map work to owners: Every critical outcome needs one owner. Shared ownership of a customer outcome is a finding.",
            "Spans and layers: Comment on spans using their reality, not a magic number from a article. Too many layers shows up as slow decisions they can name.",
            "Transitions: Who reports to whom on day one, and what is temporary. Do not leave people in limbo.",
            "Cost: Management load and role changes, qualitatively, unless they gave numbers.",
            "People impact: Be honest about role loss if the user said it exists. Do not help conceal a layoff from people who must be told through the proper process. Do not draft deceptive scripts.",
        ],
        ["A structure copied from a famous company.", "No owner for the core outcome.", "A deceptive script about a layoff."],
        "A CEO wants squads because a conference recommended them, but product decisions are already stuck between two leaders.",
        "A review that names the stuck decision, assigns one owner, and treats squads as optional rather than as the goal.",
        ["workforce-plan", "change-leadership", "succession-plan"],
    ),
    skill(
        "workforce-plan",
        "Workforce Plan",
        "Connect a hiring plan to the work and the cash, and show which roles are load-bearing.",
        "workforce plan",
        ["workforce plan", "hiring plan", "headcount plan", "capacity versus hiring"],
        ["The work to be done", "Current team and open roles", "Constraints from finance", "Skills that are scarce"],
        [
            "Demand first: What work arrives next quarter, in their words. Hiring follows demand, not a headcount habit.",
            "Capacity: Who can absorb work before a hire. A hire is a recommendation, not a reflex.",
            "Sequence: Which role unblocks the others. Hiring five roles at once without a recruiter plan is a wish.",
            "Cost: Use their pay assumptions. If pay is unknown, mark the cost as incomplete. Do not invent salaries.",
            "Contract versus hire: Note where a short need does not justify a permanent role, as a question for HR and counsel, not a classification ruling.",
            "Review point: When the plan is revisited if demand slips.",
        ],
        ["A headcount list with no link to work.", "Invented salaries.", "Hiring that ignores a cash constraint they already stated."],
        "A team asked for eight hires, and finance has capped the quarter at three.",
        "A sequenced plan of three roles that unblock the work, with the other five parked and the cash cap respected.",
        ["org-design-review", "runway-and-burn", "annual-planning-cycle"],
    ),
    skill(
        "learning-path",
        "Learning Path",
        "Build a learning path for a role from the work, with practice tasks rather than a course catalog.",
        "learning path",
        ["learning path", "upskilling plan", "training plan for a role", "skill development plan"],
        ["The skill gap in work terms", "Time available per week", "Real tasks they can practice on", "How proficiency will be judged"],
        [
            "Define proficiency: What the person will be able to do, observed on the job. Course completion is not proficiency.",
            "Sequence: Foundations, guided practice, then independent work. Skip modules that do not serve the gap.",
            "Use real work: Prefer a sanitized piece of their actual work over a generic exercise.",
            "Time box: Fit the path to the weekly time they have. A 40-hour plan for someone with two hours is not a plan.",
            "Coach: Who reviews the practice. A path with no reviewer is content, not development.",
            "Stop rule: If the gap is actually a job-design problem, say so instead of training someone to survive a broken role.",
        ],
        ["A course catalog dump.", "Completion certificates as the goal.", "Ignoring an impossible workload."],
        "An analyst is told to 'learn finance' in a month while closing the books full time.",
        "A path with a small on-the-job practice, a reviewer, and an honest note that the time budget does not fit a broad finance education.",
        ["onboarding-plan", "training-needs-analysis", "performance-review"],
    ),
    skill(
        "manager-one-on-one",
        "Manager One-on-One",
        "Set up a one-on-one that surfaces blockers and growth, not a status meeting in disguise.",
        "one-on-one guide",
        ["one on one", "1:1 agenda", "manager conversation", "skip-level questions"],
        ["How often they meet", "What the employee wants from the meeting", "Current goals", "Known sensitive topics"],
        [
            "Purpose: The employee's agenda first. Status belongs in the team channel unless it blocks them.",
            "A small standing structure: Wins, blockers, feedback both ways, and one growth question. Cut the rest.",
            "Feedback: Specific and recent. No saved-up surprise list.",
            "Notes: Shared notes the employee can see, unless a topic is confidential for a stated reason.",
            "Skip-levels: If asked, write questions that check the system, not questions that recruit complaints about a named peer.",
            "Follow-through: Every meeting ends with at most two manager actions.",
        ],
        ["A 1:1 that is only a status update.", "Secret notes used against someone later without process.", "Fishing for gossip in a skip-level."],
        "A new manager is using the weekly 1:1 to collect project status the team already tracks in a board.",
        "A guide that moves status out, puts the employee's agenda first, and caps manager actions at two.",
        ["performance-review", "stay-interview", "coaching-session"],
    ),
    skill(
        "conflict-mediation",
        "Conflict Mediation Prep",
        "Prepare a fair conversation between coworkers in conflict, without taking a side or diagnosing character.",
        "mediation prep",
        ["team conflict", "mediate a disagreement", "coworker conflict", "working relationship breakdown"],
        ["The work that is suffering", "Each person's stated concern, if known", "What the manager has already tried", "Safety issues, if any"],
        [
            "Safety first: If the user describes threats, harassment, or violence, stop mediation tips and point them to their reporting and safety process. Do not investigate as a hobby.",
            "Frame the work: The conversation is about a working agreement, not about who is the better person.",
            "Each voice: Structure time so both people state the impact on the work. No surprise audience.",
            "Interests: What each person needs in order to deliver. Positions are 'I refuse to work with them'. Interests are more useful.",
            "Agreement: A written working agreement with behaviors and a review date. No forced apology script.",
            "Escalation: If the conflict includes possible misconduct, route it to employee relations instead of a cozy mediation.",
        ],
        ["Taking a side in the prep notes.", "Mediating a harassment allegation informally.", "A forced apology."],
        "Two leads are blocking each other's releases, and one has started insulting the other in public channels.",
        "A prep that addresses the work blockage, moves insults out of public channels, and routes possible misconduct to employee relations.",
        ["employee-relations-intake", "manager-one-on-one", "stakeholder-map"],
    ),
    skill(
        "inclusive-hiring",
        "Inclusive Hiring Review",
        "Review a hiring process for avoidable bias in the funnel, using the user's data and without quotas theater.",
        "inclusive hiring review",
        ["inclusive hiring", "bias in hiring", "diverse slate", "hiring process fairness"],
        ["The stages of their process", "Drop-off data if they have it", "The job criteria", "Constraints they will not fake"],
        [
            "Look at the process before the ads: Criteria, referrals-only sourcing, and unstructured interviews are the usual leaks.",
            "Use their numbers: If they have no funnel data, the first recommendation is to count, not to claim a representation result.",
            "Criteria check: Requirements that are not tied to the work are candidates for removal. Say why.",
            "Slates: A diverse slate is a sourcing practice, not a hiring quota and not a reason to tokenise a person. Refuse tactics that treat people as props.",
            "Interview consistency: Structured questions are the practical fix. See the structured interview skill rather than repeating a sermon.",
            "Do not invent demographics: Never guess a person's identity to fill a chart.",
        ],
        ["Invented demographic statistics.", "Tokenising candidates.", "A quota dressed up as a process tip."],
        "A company hires only from employee referrals and wants a more inclusive process without changing the referral habit.",
        "A review that names referrals-only sourcing as the constraint and recommends a structured process plus real counting, with no invented demographics.",
        ["structured-interview", "job-description-writer", "hiring-scorecard"],
    ),
    skill(
        "handbook-policy-draft",
        "Handbook Policy Draft",
        "Draft a short handbook policy in plain language, marked for HR and counsel before publication.",
        "handbook policy draft",
        ["employee handbook", "HR policy draft", "workplace policy", "code of conduct section"],
        ["The behavior the policy must guide", "The current practice", "Who enforces it", "Jurisdictions they say it must cover"],
        [
            "Purpose: Why the policy exists for the workplace, in a few lines.",
            "Rules: What people should do, in plain language. Avoid legalese copied from a mega-corporation.",
            "Exceptions and reports: How to ask for an exception and how to report a breach, using their channels.",
            "Consequences: Only the consequence types they say exist. Do not invent dismissal language as a legal fact.",
            "Counsel flag: Note that local employment law may change the policy. The draft is not published as-is.",
            "Length: One or two pages. A policy nobody reads will not guide behavior.",
        ],
        ["A 30-page policy for a simple issue.", "Invented legal penalties.", "No reporting path."],
        "The company wants a remote-work policy and currently decides each request in a private chat.",
        "A two-page draft with a request path, decision criteria, and a counsel-review banner.",
        ["expense-policy", "policy-writer", "employee-relations-intake"],
    ),
    skill(
        "employee-relations-intake",
        "Employee Relations Intake",
        "Intake a workplace concern so it is routed fairly, with facts separated from conclusions.",
        "employee relations intake",
        ["employee relations", "HR complaint", "workplace complaint intake", "grievance intake"],
        ["What was reported", "Who received it and when", "Immediate safety issues", "The stated company process"],
        [
            "Safety and dignity first: Threats and harassment go to the safety and reporting path. Do not mediate those casually.",
            "Facts: What was said, when, and who has authority to look into it. Do not add motive.",
            "Conflicts: The investigator should not be the accused or their close ally. Say so if the user proposes that.",
            "Confidentiality: Need-to-know. Do not help broadcast the allegation.",
            "No retaliation: Refuse any request to punish the person who reported.",
            "Record: A neutral intake note with next step and owner. Not a verdict.",
        ],
        ["A verdict in the intake.", "Retaliation advice.", "Spreading the allegation as gossip."],
        "A team lead wants HR to 'make a complaint go away' before a client visit.",
        "An intake that records the concern, refuses to bury it, and assigns an investigator who is not the accused.",
        ["whistleblower-intake", "conflict-mediation", "pip-design"],
        ["Retaliation", "Covering up a complaint"],
    ),
    skill(
        "succession-plan",
        "Succession Plan",
        "Name successors for a few critical roles based on evidence, and identify the gap without a secret ranking of everyone's worth.",
        "succession plan",
        ["succession plan", "bench strength", "who could replace", "critical role backup"],
        ["The critical roles", "Possible successors the user names", "Evidence of readiness", "Roles with no backup"],
        [
            "Limit the scope: A handful of critical roles, not a ranking of the whole company.",
            "Ready now versus ready later: Use evidence of work already done. Potential without evidence is labeled as such.",
            "Emergency cover: Who covers the role for two weeks. That is different from a permanent successor.",
            "Gaps: A role with no cover is the finding. Do not invent a successor to make the chart look full.",
            "Development: One experience the likely successor still needs. Not a personality makeover.",
            "Sensitivity: The plan is confidential. Do not draft an email that tells people they are or are not successors unless the user has a communication plan reviewed by HR.",
        ],
        ["A stack rank of all employees.", "Naming a successor with no evidence to fill a box.", "A careless email announcing the plan."],
        "The head of implementation is a single point of failure, and nobody has led a rollout without them.",
        "A plan that names the emergency cover gap honestly and defines the experience a successor still needs.",
        ["workforce-plan", "org-design-review", "learning-path"],
    ),
    skill(
        "total-rewards-brief",
        "Total Rewards Brief",
        "Explain a person's total rewards in plain language using only components the company actually offers.",
        "total rewards brief",
        ["total rewards", "benefits explanation", "comp statement", "rewards brief"],
        ["Components the company offers", "The person's eligible parts", "What must not be promised", "Questions employees keep asking"],
        [
            "List real components: Pay, variable, time off, and benefits they confirmed. Do not add perks from other companies.",
            "Separate guaranteed from variable: A bonus target is not a promise unless they say it is guaranteed.",
            "Equity: Describe it only to the extent they explained vesting and value. Do not invent a share price.",
            "Plain language: Write the explanation an employee can read without a glossary.",
            "Questions: Answer only what policy answers. The rest go to HR. Do not give tax advice on benefits.",
            "Privacy: Do not include another employee's pay in the brief.",
        ],
        ["Implied guarantees.", "Invented share prices.", "Tax advice on benefits."],
        "Employees think the target bonus is guaranteed because the offer conversation was casual.",
        "A brief that shows the target as variable, lists only real benefits, and sends tax questions to a qualified advisor.",
        ["compensation-band", "offer-letter-checklist", "handbook-policy-draft"],
    ),
    skill(
        "coaching-session",
        "Coaching Session",
        "Plan a coaching conversation that builds a skill on real work, not a motivational speech.",
        "coaching session plan",
        ["coaching session", "coach a manager", "feedback coaching", "skill coaching"],
        ["The skill to build", "A recent work example", "What good looks like", "The coachee's goal"],
        [
            "Pick one skill: Coaching on five traits in one sitting teaches nothing.",
            "Use a real moment: A meeting, a draft, or a decision from the last two weeks.",
            "Show the gap: The difference between what happened and what good looks like, specifically.",
            "Practice: The session includes a redo, not only advice.",
            "Ask before telling: Start with the coachee's view. A lecture is not coaching.",
            "Next rep: Where they will try the skill again, and when you will review it.",
        ],
        ["A pep talk with no example.", "Five development areas in thirty minutes.", "Coaching that is really a PIP in disguise. Use the PIP skill if standards are missed repeatedly."],
        "A team lead's written updates confuse stakeholders, and the director wants a coaching plan.",
        "A session built on one recent update, with a redo in the meeting and a next rep on the following weekly note.",
        ["manager-one-on-one", "performance-review", "learning-path"],
    ),
]
